package documents

import (
	"archive/zip"
	"bytes"
	"context"
	"database/sql"
	"reflect"
	"strings"
	"testing"

	storagedb "github.com/IvanSaratov/ikc_admin_panel/backend/storage/db"
)

// TestGenerateDOCX_RecordsGenerationRun verifies that a successful DOCX
// generation writes a 'success' row to generation_runs and that the file
// name ends with .zip.
func TestGenerateDOCX_RecordsGenerationRun(t *testing.T) {
	t.Parallel()

	env := newTestEnv(t)
	protocolID, _ := env.seedFixedProtocol(t)
	ctx := context.Background()

	raw, run, err := env.svc.generateDOCXWith(ctx, env.queries, protocolID)
	if err != nil {
		t.Fatalf("GenerateDOCX: %v", err)
	}
	if len(raw) == 0 {
		t.Fatalf("GenerateDOCX produced empty bytes")
	}
	if run == nil {
		t.Fatalf("GenerateDOCX returned nil GenerationRun")
	}
	if run.Status != "success" {
		t.Errorf("run.Status = %q, want success", run.Status)
	}
	if !run.FileName.Valid || !strings.HasSuffix(run.FileName.String, ".zip") {
		t.Errorf("run.FileName = %v, want .zip suffix", run.FileName)
	}
	if run.Type != "docx" {
		t.Errorf("run.Type = %q, want docx", run.Type)
	}
}

// TestGenerateDOCX_ArchiveIsValidZip checks that the output is a real
// ZIP archive containing at least one .docx entry.
func TestGenerateDOCX_ArchiveIsValidZip(t *testing.T) {
	t.Parallel()

	env := newTestEnv(t)
	protocolID, _ := env.seedFixedProtocol(t)
	ctx := context.Background()

	raw, _, err := env.svc.generateDOCXWith(ctx, env.queries, protocolID)
	if err != nil {
		t.Fatalf("GenerateDOCX: %v", err)
	}
	r, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		t.Fatalf("open zip: %v", err)
	}
	var docxCount int
	for _, f := range r.File {
		if strings.HasSuffix(f.Name, ".docx") {
			docxCount++
		}
	}
	if docxCount == 0 {
		t.Errorf("zip archive has no .docx entries (got %d files total)", len(r.File))
	}
}

// TestNormalizeDOCX_StableAcrossRuns runs generation twice and asserts
// that NormalizeDOCX yields identical output for the XML parts (binary
// parts may contain timestamps generated by fumiama/go-docx; the test
// only asserts the structurally-relevant XML chunks are byte-stable).
func TestNormalizeDOCX_StableAcrossRuns(t *testing.T) {
	t.Parallel()

	env := newTestEnv(t)
	protocolID, _ := env.seedFixedProtocol(t)
	ctx := context.Background()

	raw1, _, err := env.svc.generateDOCXWith(ctx, env.queries, protocolID)
	if err != nil {
		t.Fatalf("first GenerateDOCX: %v", err)
	}
	raw2, _, err := env.svc.generateDOCXWith(ctx, env.queries, protocolID)
	if err != nil {
		t.Fatalf("second GenerateDOCX: %v", err)
	}

	parts1, err := NormalizeDOCX(raw1)
	if err != nil {
		t.Fatalf("NormalizeDOCX run1: %v", err)
	}
	parts2, err := NormalizeDOCX(raw2)
	if err != nil {
		t.Fatalf("NormalizeDOCX run2: %v", err)
	}

	// Compare XML parts only — binary parts may contain revision ids
	// generated by the DOCX library at write time.
	var xmlParts1, xmlParts2 []NormalizedPart
	for _, p := range parts1 {
		if p.Kind == "xml" {
			xmlParts1 = append(xmlParts1, p)
		}
	}
	for _, p := range parts2 {
		if p.Kind == "xml" {
			xmlParts2 = append(xmlParts2, p)
		}
	}
	if !reflect.DeepEqual(xmlParts1, xmlParts2) {
		t.Fatalf("NormalizeDOCX XML parts not stable across runs:\n%v\n---\n%v", xmlParts1, xmlParts2)
	}
}

// TestGenerateDOCX_AuditEntry verifies that a successful DOCX generation
// records both a "requested" and a "completed" action_log entry.
func TestGenerateDOCX_AuditEntry(t *testing.T) {
	t.Parallel()

	env := newTestEnv(t)
	protocolID, _ := env.seedFixedProtocol(t)
	ctx := context.Background()

	_, _, err := env.svc.generateDOCXWith(ctx, env.queries, protocolID)
	if err != nil {
		t.Fatalf("GenerateDOCX: %v", err)
	}

	logs, err := env.queries.ListActionLogsByEntity(ctx, storagedb.ListActionLogsByEntityParams{
		EntityType: "protocol",
		EntityID:   sql.NullInt64{Int64: protocolID, Valid: true},
	})
	if err != nil {
		t.Fatalf("ListActionLogsByEntity: %v", err)
	}
	hasRequested := false
	hasCompleted := false
	for _, l := range logs {
		if l.Action == "documents.generate.requested" {
			hasRequested = true
		}
		if l.Action == "documents.generate.completed" {
			hasCompleted = true
		}
	}
	if !hasRequested {
		t.Errorf("missing action_log entry for documents.generate.requested")
	}
	if !hasCompleted {
		t.Errorf("missing action_log entry for documents.generate.completed")
	}
}
