// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action_log.sql

package db

import (
	"context"
	"database/sql"
)

const countActionLogsFiltered = `-- name: CountActionLogsFiltered :one
SELECT COUNT(*) AS total
FROM action_log
WHERE (?1 IS NULL OR actor = ?1)
  AND (?2 IS NULL OR action = ?2)
  AND (?3 IS NULL OR entity_type = ?3)
  AND (?4 IS NULL OR created_at >= ?4)
  AND (?5 IS NULL OR created_at <= ?5)
`

type CountActionLogsFilteredParams struct {
	Actor       interface{} `json:"actor"`
	Action      interface{} `json:"action"`
	EntityType  interface{} `json:"entity_type"`
	CreatedFrom interface{} `json:"created_from"`
	CreatedTo   interface{} `json:"created_to"`
}

// D4 audit UI: count rows that match the same filter set as
// ListActionLogsFiltered. Computed in a single query so the UI can
// render "Page N of M" without pulling the full result set.
func (q *Queries) CountActionLogsFiltered(ctx context.Context, arg CountActionLogsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActionLogsFiltered,
		arg.Actor,
		arg.Action,
		arg.EntityType,
		arg.CreatedFrom,
		arg.CreatedTo,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createActionLog = `-- name: CreateActionLog :one
INSERT INTO action_log (
  actor,
  action,
  entity_type,
  entity_id,
  details,
  created_at
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, actor, action, entity_type, entity_id, details, created_at
`

type CreateActionLogParams struct {
	Actor      string         `json:"actor"`
	Action     string         `json:"action"`
	EntityType string         `json:"entity_type"`
	EntityID   sql.NullInt64  `json:"entity_id"`
	Details    sql.NullString `json:"details"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) CreateActionLog(ctx context.Context, arg CreateActionLogParams) (ActionLog, error) {
	row := q.db.QueryRowContext(ctx, createActionLog,
		arg.Actor,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
		arg.CreatedAt,
	)
	var i ActionLog
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listActionLogsByEntity = `-- name: ListActionLogsByEntity :many
SELECT id, actor, action, entity_type, entity_id, details, created_at
FROM action_log
WHERE entity_type = ? AND entity_id = ?
ORDER BY id ASC
`

type ListActionLogsByEntityParams struct {
	EntityType string        `json:"entity_type"`
	EntityID   sql.NullInt64 `json:"entity_id"`
}

// Test helper: returns all action_log rows for a given entity, ordered by
// insertion (id ASC). Used by service tests to verify audit trails.
func (q *Queries) ListActionLogsByEntity(ctx context.Context, arg ListActionLogsByEntityParams) ([]ActionLog, error) {
	rows, err := q.db.QueryContext(ctx, listActionLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionLog
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionLogsFiltered = `-- name: ListActionLogsFiltered :many
SELECT id, actor, action, entity_type, entity_id, details, created_at
FROM action_log
WHERE (?3 IS NULL OR actor = ?3)
  AND (?4 IS NULL OR action = ?4)
  AND (?5 IS NULL OR entity_type = ?5)
  AND (?6 IS NULL OR created_at >= ?6)
  AND (?7 IS NULL OR created_at <= ?7)
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListActionLogsFilteredParams struct {
	Actor       interface{} `json:"actor"`
	Action      interface{} `json:"action"`
	EntityType  interface{} `json:"entity_type"`
	CreatedFrom interface{} `json:"created_from"`
	CreatedTo   interface{} `json:"created_to"`
	Limit       int64       `json:"limit"`
	Offset      int64       `json:"offset"`
}

// D4 audit UI: list action_log rows matching the optional filters in
// actor/action/entity_type + a created_at range. Each non-empty filter
// narrows the result; an empty filter value is ignored (no constraint).
// Ordering is newest-first so the audit UI shows recent activity first;
// ties on created_at are broken by id DESC for stable pagination.
func (q *Queries) ListActionLogsFiltered(ctx context.Context, arg ListActionLogsFilteredParams) ([]ActionLog, error) {
	rows, err := q.db.QueryContext(ctx, listActionLogsFiltered,
		arg.Actor,
		arg.Action,
		arg.EntityType,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionLog
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
