// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_requests.sql

package db

import (
	"context"
	"database/sql"
)

const createClientRequest = `-- name: CreateClientRequest :one
INSERT INTO client_requests (
  employer_id,
  received_date,
  source_type,
  source_import_id,
  status,
  notes,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, employer_id, received_date, source_type, source_import_id, status, notes, created_at, updated_at
`

type CreateClientRequestParams struct {
	EmployerID     int64          `json:"employer_id"`
	ReceivedDate   string         `json:"received_date"`
	SourceType     string         `json:"source_type"`
	SourceImportID sql.NullInt64  `json:"source_import_id"`
	Status         string         `json:"status"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) CreateClientRequest(ctx context.Context, arg CreateClientRequestParams) (ClientRequest, error) {
	row := q.db.QueryRowContext(ctx, createClientRequest,
		arg.EmployerID,
		arg.ReceivedDate,
		arg.SourceType,
		arg.SourceImportID,
		arg.Status,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ClientRequest
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.ReceivedDate,
		&i.SourceType,
		&i.SourceImportID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientRequest = `-- name: GetClientRequest :one
SELECT id, employer_id, received_date, source_type, source_import_id, status, notes, created_at, updated_at
FROM client_requests
WHERE id = ?
`

func (q *Queries) GetClientRequest(ctx context.Context, id int64) (ClientRequest, error) {
	row := q.db.QueryRowContext(ctx, getClientRequest, id)
	var i ClientRequest
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.ReceivedDate,
		&i.SourceType,
		&i.SourceImportID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClientRequests = `-- name: ListClientRequests :many
SELECT id, employer_id, received_date, source_type, source_import_id, status, notes, created_at, updated_at
FROM client_requests
ORDER BY received_date DESC, id DESC
`

func (q *Queries) ListClientRequests(ctx context.Context) ([]ClientRequest, error) {
	rows, err := q.db.QueryContext(ctx, listClientRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientRequest
	for rows.Next() {
		var i ClientRequest
		if err := rows.Scan(
			&i.ID,
			&i.EmployerID,
			&i.ReceivedDate,
			&i.SourceType,
			&i.SourceImportID,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientRequestsByStatus = `-- name: ListClientRequestsByStatus :many
SELECT id, employer_id, received_date, source_type, source_import_id, status, notes, created_at, updated_at
FROM client_requests
WHERE status = ?
ORDER BY received_date DESC, id DESC
`

func (q *Queries) ListClientRequestsByStatus(ctx context.Context, status string) ([]ClientRequest, error) {
	rows, err := q.db.QueryContext(ctx, listClientRequestsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientRequest
	for rows.Next() {
		var i ClientRequest
		if err := rows.Scan(
			&i.ID,
			&i.EmployerID,
			&i.ReceivedDate,
			&i.SourceType,
			&i.SourceImportID,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClientRequestSourceImport = `-- name: SetClientRequestSourceImport :one
UPDATE client_requests
SET source_import_id = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, employer_id, received_date, source_type, source_import_id, status, notes, created_at, updated_at
`

type SetClientRequestSourceImportParams struct {
	SourceImportID sql.NullInt64 `json:"source_import_id"`
	UpdatedAt      string        `json:"updated_at"`
	ID             int64         `json:"id"`
}

func (q *Queries) SetClientRequestSourceImport(ctx context.Context, arg SetClientRequestSourceImportParams) (ClientRequest, error) {
	row := q.db.QueryRowContext(ctx, setClientRequestSourceImport, arg.SourceImportID, arg.UpdatedAt, arg.ID)
	var i ClientRequest
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.ReceivedDate,
		&i.SourceType,
		&i.SourceImportID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientRequestStatus = `-- name: UpdateClientRequestStatus :one
UPDATE client_requests
SET status = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, employer_id, received_date, source_type, source_import_id, status, notes, created_at, updated_at
`

type UpdateClientRequestStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateClientRequestStatus(ctx context.Context, arg UpdateClientRequestStatusParams) (ClientRequest, error) {
	row := q.db.QueryRowContext(ctx, updateClientRequestStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i ClientRequest
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.ReceivedDate,
		&i.SourceType,
		&i.SourceImportID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
