// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employers.sql

package db

import (
	"context"
)

const createEmployer = `-- name: CreateEmployer :one
INSERT INTO employers (
  inn,
  inn_normalized,
  canonical_name,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, inn, inn_normalized, canonical_name, created_at, updated_at, status
`

type CreateEmployerParams struct {
	Inn           string `json:"inn"`
	InnNormalized string `json:"inn_normalized"`
	CanonicalName string `json:"canonical_name"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) CreateEmployer(ctx context.Context, arg CreateEmployerParams) (Employer, error) {
	row := q.db.QueryRowContext(ctx, createEmployer,
		arg.Inn,
		arg.InnNormalized,
		arg.CanonicalName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Employer
	err := row.Scan(
		&i.ID,
		&i.Inn,
		&i.InnNormalized,
		&i.CanonicalName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const deactivateEmployer = `-- name: DeactivateEmployer :one
UPDATE employers
SET status = 'inactive', updated_at = ?
WHERE id = ? AND status = 'active'
RETURNING id, inn, inn_normalized, canonical_name, created_at, updated_at, status
`

type DeactivateEmployerParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

// After 003 added `status` to employers, this flips the soft-delete flag
// and records the transition in the audit log. Idempotent: a no-op when
// status is already 'inactive' (no rows updated).
func (q *Queries) DeactivateEmployer(ctx context.Context, arg DeactivateEmployerParams) (Employer, error) {
	row := q.db.QueryRowContext(ctx, deactivateEmployer, arg.UpdatedAt, arg.ID)
	var i Employer
	err := row.Scan(
		&i.ID,
		&i.Inn,
		&i.InnNormalized,
		&i.CanonicalName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getEmployer = `-- name: GetEmployer :one
SELECT id, inn, inn_normalized, canonical_name, created_at, updated_at, status
FROM employers
WHERE id = ?
`

func (q *Queries) GetEmployer(ctx context.Context, id int64) (Employer, error) {
	row := q.db.QueryRowContext(ctx, getEmployer, id)
	var i Employer
	err := row.Scan(
		&i.ID,
		&i.Inn,
		&i.InnNormalized,
		&i.CanonicalName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getEmployerByID = `-- name: GetEmployerByID :one
SELECT id, inn, inn_normalized, canonical_name, created_at, updated_at, status
FROM employers
WHERE id = ?
`

func (q *Queries) GetEmployerByID(ctx context.Context, id int64) (Employer, error) {
	row := q.db.QueryRowContext(ctx, getEmployerByID, id)
	var i Employer
	err := row.Scan(
		&i.ID,
		&i.Inn,
		&i.InnNormalized,
		&i.CanonicalName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getEmployerByNormalizedINN = `-- name: GetEmployerByNormalizedINN :one
SELECT id, inn, inn_normalized, canonical_name, created_at, updated_at, status
FROM employers
WHERE inn_normalized = ?
`

func (q *Queries) GetEmployerByNormalizedINN(ctx context.Context, innNormalized string) (Employer, error) {
	row := q.db.QueryRowContext(ctx, getEmployerByNormalizedINN, innNormalized)
	var i Employer
	err := row.Scan(
		&i.ID,
		&i.Inn,
		&i.InnNormalized,
		&i.CanonicalName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const listEmployers = `-- name: ListEmployers :many
SELECT id, inn, inn_normalized, canonical_name, created_at, updated_at, status
FROM employers
ORDER BY canonical_name
`

func (q *Queries) ListEmployers(ctx context.Context) ([]Employer, error) {
	rows, err := q.db.QueryContext(ctx, listEmployers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employer
	for rows.Next() {
		var i Employer
		if err := rows.Scan(
			&i.ID,
			&i.Inn,
			&i.InnNormalized,
			&i.CanonicalName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEmployers = `-- name: SearchEmployers :many
SELECT id, inn, inn_normalized, canonical_name, created_at, updated_at, status
FROM employers
WHERE canonical_name LIKE ? OR inn_normalized LIKE ?
ORDER BY canonical_name
`

type SearchEmployersParams struct {
	CanonicalName string `json:"canonical_name"`
	InnNormalized string `json:"inn_normalized"`
}

func (q *Queries) SearchEmployers(ctx context.Context, arg SearchEmployersParams) ([]Employer, error) {
	rows, err := q.db.QueryContext(ctx, searchEmployers, arg.CanonicalName, arg.InnNormalized)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employer
	for rows.Next() {
		var i Employer
		if err := rows.Scan(
			&i.ID,
			&i.Inn,
			&i.InnNormalized,
			&i.CanonicalName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployer = `-- name: UpdateEmployer :one
UPDATE employers
SET inn = ?,
    inn_normalized = ?,
    canonical_name = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, inn, inn_normalized, canonical_name, created_at, updated_at, status
`

type UpdateEmployerParams struct {
	Inn           string `json:"inn"`
	InnNormalized string `json:"inn_normalized"`
	CanonicalName string `json:"canonical_name"`
	UpdatedAt     string `json:"updated_at"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateEmployer(ctx context.Context, arg UpdateEmployerParams) (Employer, error) {
	row := q.db.QueryRowContext(ctx, updateEmployer,
		arg.Inn,
		arg.InnNormalized,
		arg.CanonicalName,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Employer
	err := row.Scan(
		&i.ID,
		&i.Inn,
		&i.InnNormalized,
		&i.CanonicalName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
