// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generation_runs.sql

package db

import (
	"context"
	"database/sql"
)

const createGenerationRun = `-- name: CreateGenerationRun :one
INSERT INTO generation_runs (
  protocol_id,
  type,
  status,
  file_name,
  generated_at,
  error_message,
  created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, protocol_id, type, status, file_name, generated_at, error_message, created_at
`

type CreateGenerationRunParams struct {
	ProtocolID   int64          `json:"protocol_id"`
	Type         string         `json:"type"`
	Status       string         `json:"status"`
	FileName     sql.NullString `json:"file_name"`
	GeneratedAt  string         `json:"generated_at"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    string         `json:"created_at"`
}

// Insert a new generation_runs row. status is one of 'success' / 'failed'
// / 'stale' (the schema CHECK constraint). file_name and error_message
// are nullable.
func (q *Queries) CreateGenerationRun(ctx context.Context, arg CreateGenerationRunParams) (GenerationRun, error) {
	row := q.db.QueryRowContext(ctx, createGenerationRun,
		arg.ProtocolID,
		arg.Type,
		arg.Status,
		arg.FileName,
		arg.GeneratedAt,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.Type,
		&i.Status,
		&i.FileName,
		&i.GeneratedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getGenerationRun = `-- name: GetGenerationRun :one
SELECT id, protocol_id, type, status, file_name, generated_at, error_message, created_at
FROM generation_runs
WHERE id = ?
`

// Look up a generation_runs row by id. Used by the download handler to
// serve a previously generated file. Returns sql.ErrNoRows when missing.
func (q *Queries) GetGenerationRun(ctx context.Context, id int64) (GenerationRun, error) {
	row := q.db.QueryRowContext(ctx, getGenerationRun, id)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.Type,
		&i.Status,
		&i.FileName,
		&i.GeneratedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listGenerationRunsForProtocol = `-- name: ListGenerationRunsForProtocol :many
SELECT id, protocol_id, type, status, file_name, generated_at, error_message, created_at
FROM generation_runs
WHERE protocol_id = ?
ORDER BY generated_at DESC, id DESC
`

// Recent generations for a single protocol, newest first. Used by the
// detail view to show the "last downloads" list.
func (q *Queries) ListGenerationRunsForProtocol(ctx context.Context, protocolID int64) ([]GenerationRun, error) {
	rows, err := q.db.QueryContext(ctx, listGenerationRunsForProtocol, protocolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationRun
	for rows.Next() {
		var i GenerationRun
		if err := rows.Scan(
			&i.ID,
			&i.ProtocolID,
			&i.Type,
			&i.Status,
			&i.FileName,
			&i.GeneratedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
