// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: imports.sql

package db

import (
	"context"
	"database/sql"
)

const createImport = `-- name: CreateImport :one
INSERT INTO imports (
  source_type,
  source_file_name,
  source_sha256,
  uploaded_by_actor,
  received_at,
  status,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, source_type, source_file_name, source_sha256, uploaded_by_actor, received_at, status, created_at, updated_at
`

type CreateImportParams struct {
	SourceType      string         `json:"source_type"`
	SourceFileName  sql.NullString `json:"source_file_name"`
	SourceSha256    sql.NullString `json:"source_sha256"`
	UploadedByActor string         `json:"uploaded_by_actor"`
	ReceivedAt      string         `json:"received_at"`
	Status          string         `json:"status"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

func (q *Queries) CreateImport(ctx context.Context, arg CreateImportParams) (Import, error) {
	row := q.db.QueryRowContext(ctx, createImport,
		arg.SourceType,
		arg.SourceFileName,
		arg.SourceSha256,
		arg.UploadedByActor,
		arg.ReceivedAt,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.SourceFileName,
		&i.SourceSha256,
		&i.UploadedByActor,
		&i.ReceivedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImportRow = `-- name: CreateImportRow :one
INSERT INTO import_rows (
  import_id,
  row_number,
  raw_data,
  created_at
)
VALUES (?, ?, ?, ?)
RETURNING id, import_id, row_number, raw_data, created_at
`

type CreateImportRowParams struct {
	ImportID  int64  `json:"import_id"`
	RowNumber int64  `json:"row_number"`
	RawData   string `json:"raw_data"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateImportRow(ctx context.Context, arg CreateImportRowParams) (ImportRow, error) {
	row := q.db.QueryRowContext(ctx, createImportRow,
		arg.ImportID,
		arg.RowNumber,
		arg.RawData,
		arg.CreatedAt,
	)
	var i ImportRow
	err := row.Scan(
		&i.ID,
		&i.ImportID,
		&i.RowNumber,
		&i.RawData,
		&i.CreatedAt,
	)
	return i, err
}

const getImportByID = `-- name: GetImportByID :one
SELECT id, source_type, source_file_name, source_sha256, uploaded_by_actor, received_at, status, created_at, updated_at
FROM imports
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetImportByID(ctx context.Context, id int64) (Import, error) {
	row := q.db.QueryRowContext(ctx, getImportByID, id)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.SourceFileName,
		&i.SourceSha256,
		&i.UploadedByActor,
		&i.ReceivedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportRowByID = `-- name: GetImportRowByID :one
SELECT id, import_id, row_number, raw_data, created_at
FROM import_rows
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetImportRowByID(ctx context.Context, id int64) (ImportRow, error) {
	row := q.db.QueryRowContext(ctx, getImportRowByID, id)
	var i ImportRow
	err := row.Scan(
		&i.ID,
		&i.ImportID,
		&i.RowNumber,
		&i.RawData,
		&i.CreatedAt,
	)
	return i, err
}

const listImportRows = `-- name: ListImportRows :many
SELECT id, import_id, row_number, raw_data, created_at
FROM import_rows
WHERE import_id = ?
ORDER BY row_number ASC, id ASC
`

func (q *Queries) ListImportRows(ctx context.Context, importID int64) ([]ImportRow, error) {
	rows, err := q.db.QueryContext(ctx, listImportRows, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportRow
	for rows.Next() {
		var i ImportRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.RowNumber,
			&i.RawData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImports = `-- name: ListImports :many
SELECT id, source_type, source_file_name, source_sha256, uploaded_by_actor, received_at, status, created_at, updated_at
FROM imports
ORDER BY received_at DESC, id DESC
`

func (q *Queries) ListImports(ctx context.Context) ([]Import, error) {
	rows, err := q.db.QueryContext(ctx, listImports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Import
	for rows.Next() {
		var i Import
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.SourceFileName,
			&i.SourceSha256,
			&i.UploadedByActor,
			&i.ReceivedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportStatus = `-- name: UpdateImportStatus :exec
UPDATE imports
SET status = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateImportStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateImportStatus(ctx context.Context, arg UpdateImportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateImportStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
