// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_sheets.sql

package db

import (
	"context"
	"database/sql"
)

const completeImportSheetStaging = `-- name: CompleteImportSheetStaging :one
UPDATE import_sheets
SET rows_found = ?1,
    rows_staged = ?2,
    status = 'staged',
    updated_at = ?3
WHERE import_sheets.id = ?4
  AND import_sheets.import_id = ?5
  AND import_sheets.rows_found <= ?1
  AND import_sheets.rows_staged <= ?2
  AND import_sheets.status IN ('pending', 'parsing', 'staged')
  AND EXISTS (
    SELECT 1
    FROM imports AS owned_import
    WHERE owned_import.id = ?5
      AND owned_import.status = 'processing'
      AND owned_import.phase = 'staging'
      AND owned_import.lease_owner = ?6
      AND owned_import.lease_expires_at >= ?7
  )
RETURNING id, import_id, sheet_name, sheet_order, sheet_profile, header_map, rows_found, rows_staged, status, created_at, updated_at
`

type CompleteImportSheetStagingParams struct {
	RowsFound  int64          `json:"rows_found"`
	RowsStaged int64          `json:"rows_staged"`
	UpdatedAt  string         `json:"updated_at"`
	SheetID    int64          `json:"sheet_id"`
	ImportID   int64          `json:"import_id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
	Now        sql.NullString `json:"now"`
}

func (q *Queries) CompleteImportSheetStaging(ctx context.Context, arg CompleteImportSheetStagingParams) (ImportSheet, error) {
	row := q.db.QueryRowContext(ctx, completeImportSheetStaging,
		arg.RowsFound,
		arg.RowsStaged,
		arg.UpdatedAt,
		arg.SheetID,
		arg.ImportID,
		arg.LeaseOwner,
		arg.Now,
	)
	var i ImportSheet
	err := row.Scan(
		&i.ID,
		&i.ImportID,
		&i.SheetName,
		&i.SheetOrder,
		&i.SheetProfile,
		&i.HeaderMap,
		&i.RowsFound,
		&i.RowsStaged,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImportSheet = `-- name: CreateImportSheet :one
INSERT INTO import_sheets (
  import_id,
  sheet_name,
  sheet_order,
  sheet_profile,
  header_map,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, import_id, sheet_name, sheet_order, sheet_profile, header_map, rows_found, rows_staged, status, created_at, updated_at
`

type CreateImportSheetParams struct {
	ImportID     int64  `json:"import_id"`
	SheetName    string `json:"sheet_name"`
	SheetOrder   int64  `json:"sheet_order"`
	SheetProfile string `json:"sheet_profile"`
	HeaderMap    string `json:"header_map"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) CreateImportSheet(ctx context.Context, arg CreateImportSheetParams) (ImportSheet, error) {
	row := q.db.QueryRowContext(ctx, createImportSheet,
		arg.ImportID,
		arg.SheetName,
		arg.SheetOrder,
		arg.SheetProfile,
		arg.HeaderMap,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ImportSheet
	err := row.Scan(
		&i.ID,
		&i.ImportID,
		&i.SheetName,
		&i.SheetOrder,
		&i.SheetProfile,
		&i.HeaderMap,
		&i.RowsFound,
		&i.RowsStaged,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportSheet = `-- name: GetImportSheet :one
SELECT id, import_id, sheet_name, sheet_order, sheet_profile, header_map, rows_found, rows_staged, status, created_at, updated_at
FROM import_sheets
WHERE import_id = ? AND sheet_name = ?
LIMIT 1
`

type GetImportSheetParams struct {
	ImportID  int64  `json:"import_id"`
	SheetName string `json:"sheet_name"`
}

func (q *Queries) GetImportSheet(ctx context.Context, arg GetImportSheetParams) (ImportSheet, error) {
	row := q.db.QueryRowContext(ctx, getImportSheet, arg.ImportID, arg.SheetName)
	var i ImportSheet
	err := row.Scan(
		&i.ID,
		&i.ImportID,
		&i.SheetName,
		&i.SheetOrder,
		&i.SheetProfile,
		&i.HeaderMap,
		&i.RowsFound,
		&i.RowsStaged,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listImportSheets = `-- name: ListImportSheets :many
SELECT id, import_id, sheet_name, sheet_order, sheet_profile, header_map, rows_found, rows_staged, status, created_at, updated_at
FROM import_sheets
WHERE import_id = ?
ORDER BY sheet_order ASC, id ASC
`

func (q *Queries) ListImportSheets(ctx context.Context, importID int64) ([]ImportSheet, error) {
	rows, err := q.db.QueryContext(ctx, listImportSheets, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportSheet
	for rows.Next() {
		var i ImportSheet
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.SheetName,
			&i.SheetOrder,
			&i.SheetProfile,
			&i.HeaderMap,
			&i.RowsFound,
			&i.RowsStaged,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportSheetProgress = `-- name: UpdateImportSheetProgress :one
UPDATE import_sheets
SET rows_found = ?,
    rows_staged = ?,
    status = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, import_id, sheet_name, sheet_order, sheet_profile, header_map, rows_found, rows_staged, status, created_at, updated_at
`

type UpdateImportSheetProgressParams struct {
	RowsFound  int64  `json:"rows_found"`
	RowsStaged int64  `json:"rows_staged"`
	Status     string `json:"status"`
	UpdatedAt  string `json:"updated_at"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateImportSheetProgress(ctx context.Context, arg UpdateImportSheetProgressParams) (ImportSheet, error) {
	row := q.db.QueryRowContext(ctx, updateImportSheetProgress,
		arg.RowsFound,
		arg.RowsStaged,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ImportSheet
	err := row.Scan(
		&i.ID,
		&i.ImportID,
		&i.SheetName,
		&i.SheetOrder,
		&i.SheetProfile,
		&i.HeaderMap,
		&i.RowsFound,
		&i.RowsStaged,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImportSheetStagingProgress = `-- name: UpdateImportSheetStagingProgress :one
UPDATE import_sheets
SET rows_found = ?1,
    rows_staged = ?2,
    status = 'parsing',
    updated_at = ?3
WHERE import_sheets.id = ?4
  AND import_sheets.import_id = ?5
  AND import_sheets.rows_found <= ?1
  AND import_sheets.rows_staged <= ?2
  AND import_sheets.status IN ('pending', 'parsing')
  AND EXISTS (
    SELECT 1
    FROM imports AS owned_import
    WHERE owned_import.id = ?5
      AND owned_import.status = 'processing'
      AND owned_import.phase = 'staging'
      AND owned_import.lease_owner = ?6
      AND owned_import.lease_expires_at >= ?7
  )
RETURNING id, import_id, sheet_name, sheet_order, sheet_profile, header_map, rows_found, rows_staged, status, created_at, updated_at
`

type UpdateImportSheetStagingProgressParams struct {
	RowsFound  int64          `json:"rows_found"`
	RowsStaged int64          `json:"rows_staged"`
	UpdatedAt  string         `json:"updated_at"`
	SheetID    int64          `json:"sheet_id"`
	ImportID   int64          `json:"import_id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
	Now        sql.NullString `json:"now"`
}

func (q *Queries) UpdateImportSheetStagingProgress(ctx context.Context, arg UpdateImportSheetStagingProgressParams) (ImportSheet, error) {
	row := q.db.QueryRowContext(ctx, updateImportSheetStagingProgress,
		arg.RowsFound,
		arg.RowsStaged,
		arg.UpdatedAt,
		arg.SheetID,
		arg.ImportID,
		arg.LeaseOwner,
		arg.Now,
	)
	var i ImportSheet
	err := row.Scan(
		&i.ID,
		&i.ImportID,
		&i.SheetName,
		&i.SheetOrder,
		&i.SheetProfile,
		&i.HeaderMap,
		&i.RowsFound,
		&i.RowsStaged,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
