// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_row_issues.sql

package db

import (
	"context"
	"database/sql"
)

const createImportRowIssue = `-- name: CreateImportRowIssue :one
INSERT INTO import_row_issues (
  import_row_id,
  field,
  code,
  severity,
  message,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, import_row_id, field, code, severity, message, resolution, resolved_by_actor, resolved_at, created_at, updated_at
`

type CreateImportRowIssueParams struct {
	ImportRowID int64  `json:"import_row_id"`
	Field       string `json:"field"`
	Code        string `json:"code"`
	Severity    string `json:"severity"`
	Message     string `json:"message"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreateImportRowIssue(ctx context.Context, arg CreateImportRowIssueParams) (ImportRowIssue, error) {
	row := q.db.QueryRowContext(ctx, createImportRowIssue,
		arg.ImportRowID,
		arg.Field,
		arg.Code,
		arg.Severity,
		arg.Message,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ImportRowIssue
	err := row.Scan(
		&i.ID,
		&i.ImportRowID,
		&i.Field,
		&i.Code,
		&i.Severity,
		&i.Message,
		&i.Resolution,
		&i.ResolvedByActor,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteImportRowIssues = `-- name: DeleteImportRowIssues :exec
DELETE FROM import_row_issues
WHERE import_row_id = ?
`

func (q *Queries) DeleteImportRowIssues(ctx context.Context, importRowID int64) error {
	_, err := q.db.ExecContext(ctx, deleteImportRowIssues, importRowID)
	return err
}

const listImportRowIssues = `-- name: ListImportRowIssues :many
SELECT id, import_row_id, field, code, severity, message, resolution, resolved_by_actor, resolved_at, created_at, updated_at
FROM import_row_issues
WHERE import_row_id = ?
ORDER BY severity DESC, field ASC, code ASC, id ASC
`

func (q *Queries) ListImportRowIssues(ctx context.Context, importRowID int64) ([]ImportRowIssue, error) {
	rows, err := q.db.QueryContext(ctx, listImportRowIssues, importRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportRowIssue
	for rows.Next() {
		var i ImportRowIssue
		if err := rows.Scan(
			&i.ID,
			&i.ImportRowID,
			&i.Field,
			&i.Code,
			&i.Severity,
			&i.Message,
			&i.Resolution,
			&i.ResolvedByActor,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveImportRowIssue = `-- name: ResolveImportRowIssue :one
UPDATE import_row_issues
SET resolution = ?,
    resolved_by_actor = ?,
    resolved_at = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, import_row_id, field, code, severity, message, resolution, resolved_by_actor, resolved_at, created_at, updated_at
`

type ResolveImportRowIssueParams struct {
	Resolution      sql.NullString `json:"resolution"`
	ResolvedByActor sql.NullString `json:"resolved_by_actor"`
	ResolvedAt      sql.NullString `json:"resolved_at"`
	UpdatedAt       string         `json:"updated_at"`
	ID              int64          `json:"id"`
}

func (q *Queries) ResolveImportRowIssue(ctx context.Context, arg ResolveImportRowIssueParams) (ImportRowIssue, error) {
	row := q.db.QueryRowContext(ctx, resolveImportRowIssue,
		arg.Resolution,
		arg.ResolvedByActor,
		arg.ResolvedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ImportRowIssue
	err := row.Scan(
		&i.ID,
		&i.ImportRowID,
		&i.Field,
		&i.Code,
		&i.Severity,
		&i.Message,
		&i.Resolution,
		&i.ResolvedByActor,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
