// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legacy_import_rows.sql

package db

import (
	"context"
	"database/sql"
)

const createLegacyImportRow = `-- name: CreateLegacyImportRow :one
INSERT INTO legacy_import_rows (
  import_row_id,
  source_fingerprint,
  extra_fields,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?)
RETURNING import_row_id, source_fingerprint, employer_name, inn_normalized, last_name, first_name, middle_name, snils_normalized, email_normalized, position, department, program_text, training_start_date, training_end_date, protocol_number, protocol_date, assessment_result, mintrud_registry_number, source_reference, moodle_username, moodle_email, extra_fields, status, version, employer_id, worker_id, worker_employer_id, program_id, client_request_id, training_record_id, protocol_id, protocol_participant_id, moodle_account_id, created_at, updated_at
`

type CreateLegacyImportRowParams struct {
	ImportRowID       int64  `json:"import_row_id"`
	SourceFingerprint string `json:"source_fingerprint"`
	ExtraFields       string `json:"extra_fields"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) CreateLegacyImportRow(ctx context.Context, arg CreateLegacyImportRowParams) (LegacyImportRow, error) {
	row := q.db.QueryRowContext(ctx, createLegacyImportRow,
		arg.ImportRowID,
		arg.SourceFingerprint,
		arg.ExtraFields,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LegacyImportRow
	err := row.Scan(
		&i.ImportRowID,
		&i.SourceFingerprint,
		&i.EmployerName,
		&i.InnNormalized,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.SnilsNormalized,
		&i.EmailNormalized,
		&i.Position,
		&i.Department,
		&i.ProgramText,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.ProtocolNumber,
		&i.ProtocolDate,
		&i.AssessmentResult,
		&i.MintrudRegistryNumber,
		&i.SourceReference,
		&i.MoodleUsername,
		&i.MoodleEmail,
		&i.ExtraFields,
		&i.Status,
		&i.Version,
		&i.EmployerID,
		&i.WorkerID,
		&i.WorkerEmployerID,
		&i.ProgramID,
		&i.ClientRequestID,
		&i.TrainingRecordID,
		&i.ProtocolID,
		&i.ProtocolParticipantID,
		&i.MoodleAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLegacyImportRow = `-- name: GetLegacyImportRow :one
SELECT import_row_id, source_fingerprint, employer_name, inn_normalized, last_name, first_name, middle_name, snils_normalized, email_normalized, position, department, program_text, training_start_date, training_end_date, protocol_number, protocol_date, assessment_result, mintrud_registry_number, source_reference, moodle_username, moodle_email, extra_fields, status, version, employer_id, worker_id, worker_employer_id, program_id, client_request_id, training_record_id, protocol_id, protocol_participant_id, moodle_account_id, created_at, updated_at
FROM legacy_import_rows
WHERE import_row_id = ?
LIMIT 1
`

func (q *Queries) GetLegacyImportRow(ctx context.Context, importRowID int64) (LegacyImportRow, error) {
	row := q.db.QueryRowContext(ctx, getLegacyImportRow, importRowID)
	var i LegacyImportRow
	err := row.Scan(
		&i.ImportRowID,
		&i.SourceFingerprint,
		&i.EmployerName,
		&i.InnNormalized,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.SnilsNormalized,
		&i.EmailNormalized,
		&i.Position,
		&i.Department,
		&i.ProgramText,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.ProtocolNumber,
		&i.ProtocolDate,
		&i.AssessmentResult,
		&i.MintrudRegistryNumber,
		&i.SourceReference,
		&i.MoodleUsername,
		&i.MoodleEmail,
		&i.ExtraFields,
		&i.Status,
		&i.Version,
		&i.EmployerID,
		&i.WorkerID,
		&i.WorkerEmployerID,
		&i.ProgramID,
		&i.ClientRequestID,
		&i.TrainingRecordID,
		&i.ProtocolID,
		&i.ProtocolParticipantID,
		&i.MoodleAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllLegacyImportRowsPage = `-- name: ListAllLegacyImportRowsPage :many
SELECT
  import_rows.id,
  import_rows.import_id,
  import_rows.sheet_name,
  import_rows.row_number,
  import_rows.raw_data,
  import_rows.created_at,
  import_sheets.sheet_order,
  legacy_import_rows.import_row_id, legacy_import_rows.source_fingerprint, legacy_import_rows.employer_name, legacy_import_rows.inn_normalized, legacy_import_rows.last_name, legacy_import_rows.first_name, legacy_import_rows.middle_name, legacy_import_rows.snils_normalized, legacy_import_rows.email_normalized, legacy_import_rows.position, legacy_import_rows.department, legacy_import_rows.program_text, legacy_import_rows.training_start_date, legacy_import_rows.training_end_date, legacy_import_rows.protocol_number, legacy_import_rows.protocol_date, legacy_import_rows.assessment_result, legacy_import_rows.mintrud_registry_number, legacy_import_rows.source_reference, legacy_import_rows.moodle_username, legacy_import_rows.moodle_email, legacy_import_rows.extra_fields, legacy_import_rows.status, legacy_import_rows.version, legacy_import_rows.employer_id, legacy_import_rows.worker_id, legacy_import_rows.worker_employer_id, legacy_import_rows.program_id, legacy_import_rows.client_request_id, legacy_import_rows.training_record_id, legacy_import_rows.protocol_id, legacy_import_rows.protocol_participant_id, legacy_import_rows.moodle_account_id, legacy_import_rows.created_at, legacy_import_rows.updated_at
FROM import_rows
JOIN import_sheets
  ON import_sheets.import_id = import_rows.import_id
 AND import_sheets.sheet_name = import_rows.sheet_name
JOIN legacy_import_rows
  ON legacy_import_rows.import_row_id = import_rows.id
WHERE import_rows.import_id = ?1
  AND (
    import_sheets.sheet_order > ?2
    OR (
      import_sheets.sheet_order = ?2
      AND import_rows.row_number > ?3
    )
    OR (
      import_sheets.sheet_order = ?2
      AND import_rows.row_number = ?3
      AND import_rows.id > ?4
    )
  )
ORDER BY import_sheets.sheet_order ASC, import_rows.row_number ASC, import_rows.id ASC
LIMIT ?5
`

type ListAllLegacyImportRowsPageParams struct {
	ImportID        int64 `json:"import_id"`
	AfterSheetOrder int64 `json:"after_sheet_order"`
	AfterRowNumber  int64 `json:"after_row_number"`
	AfterID         int64 `json:"after_id"`
	PageSize        int64 `json:"page_size"`
}

type ListAllLegacyImportRowsPageRow struct {
	ID                    int64          `json:"id"`
	ImportID              int64          `json:"import_id"`
	SheetName             string         `json:"sheet_name"`
	RowNumber             int64          `json:"row_number"`
	RawData               string         `json:"raw_data"`
	CreatedAt             string         `json:"created_at"`
	SheetOrder            int64          `json:"sheet_order"`
	ImportRowID           int64          `json:"import_row_id"`
	SourceFingerprint     string         `json:"source_fingerprint"`
	EmployerName          sql.NullString `json:"employer_name"`
	InnNormalized         sql.NullString `json:"inn_normalized"`
	LastName              sql.NullString `json:"last_name"`
	FirstName             sql.NullString `json:"first_name"`
	MiddleName            sql.NullString `json:"middle_name"`
	SnilsNormalized       sql.NullString `json:"snils_normalized"`
	EmailNormalized       sql.NullString `json:"email_normalized"`
	Position              sql.NullString `json:"position"`
	Department            sql.NullString `json:"department"`
	ProgramText           sql.NullString `json:"program_text"`
	TrainingStartDate     sql.NullString `json:"training_start_date"`
	TrainingEndDate       sql.NullString `json:"training_end_date"`
	ProtocolNumber        sql.NullString `json:"protocol_number"`
	ProtocolDate          sql.NullString `json:"protocol_date"`
	AssessmentResult      sql.NullString `json:"assessment_result"`
	MintrudRegistryNumber sql.NullString `json:"mintrud_registry_number"`
	SourceReference       sql.NullString `json:"source_reference"`
	MoodleUsername        sql.NullString `json:"moodle_username"`
	MoodleEmail           sql.NullString `json:"moodle_email"`
	ExtraFields           string         `json:"extra_fields"`
	Status                string         `json:"status"`
	Version               int64          `json:"version"`
	EmployerID            sql.NullInt64  `json:"employer_id"`
	WorkerID              sql.NullInt64  `json:"worker_id"`
	WorkerEmployerID      sql.NullInt64  `json:"worker_employer_id"`
	ProgramID             sql.NullInt64  `json:"program_id"`
	ClientRequestID       sql.NullInt64  `json:"client_request_id"`
	TrainingRecordID      sql.NullInt64  `json:"training_record_id"`
	ProtocolID            sql.NullInt64  `json:"protocol_id"`
	ProtocolParticipantID sql.NullInt64  `json:"protocol_participant_id"`
	MoodleAccountID       sql.NullInt64  `json:"moodle_account_id"`
	CreatedAt_2           string         `json:"created_at_2"`
	UpdatedAt             string         `json:"updated_at"`
}

func (q *Queries) ListAllLegacyImportRowsPage(ctx context.Context, arg ListAllLegacyImportRowsPageParams) ([]ListAllLegacyImportRowsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllLegacyImportRowsPage,
		arg.ImportID,
		arg.AfterSheetOrder,
		arg.AfterRowNumber,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllLegacyImportRowsPageRow
	for rows.Next() {
		var i ListAllLegacyImportRowsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.SheetName,
			&i.RowNumber,
			&i.RawData,
			&i.CreatedAt,
			&i.SheetOrder,
			&i.ImportRowID,
			&i.SourceFingerprint,
			&i.EmployerName,
			&i.InnNormalized,
			&i.LastName,
			&i.FirstName,
			&i.MiddleName,
			&i.SnilsNormalized,
			&i.EmailNormalized,
			&i.Position,
			&i.Department,
			&i.ProgramText,
			&i.TrainingStartDate,
			&i.TrainingEndDate,
			&i.ProtocolNumber,
			&i.ProtocolDate,
			&i.AssessmentResult,
			&i.MintrudRegistryNumber,
			&i.SourceReference,
			&i.MoodleUsername,
			&i.MoodleEmail,
			&i.ExtraFields,
			&i.Status,
			&i.Version,
			&i.EmployerID,
			&i.WorkerID,
			&i.WorkerEmployerID,
			&i.ProgramID,
			&i.ClientRequestID,
			&i.TrainingRecordID,
			&i.ProtocolID,
			&i.ProtocolParticipantID,
			&i.MoodleAccountID,
			&i.CreatedAt_2,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacyImportRowsByStatusPage = `-- name: ListLegacyImportRowsByStatusPage :many
SELECT
  import_rows.id,
  import_rows.import_id,
  import_rows.sheet_name,
  import_rows.row_number,
  import_rows.raw_data,
  import_rows.created_at,
  import_sheets.sheet_order,
  legacy_import_rows.import_row_id, legacy_import_rows.source_fingerprint, legacy_import_rows.employer_name, legacy_import_rows.inn_normalized, legacy_import_rows.last_name, legacy_import_rows.first_name, legacy_import_rows.middle_name, legacy_import_rows.snils_normalized, legacy_import_rows.email_normalized, legacy_import_rows.position, legacy_import_rows.department, legacy_import_rows.program_text, legacy_import_rows.training_start_date, legacy_import_rows.training_end_date, legacy_import_rows.protocol_number, legacy_import_rows.protocol_date, legacy_import_rows.assessment_result, legacy_import_rows.mintrud_registry_number, legacy_import_rows.source_reference, legacy_import_rows.moodle_username, legacy_import_rows.moodle_email, legacy_import_rows.extra_fields, legacy_import_rows.status, legacy_import_rows.version, legacy_import_rows.employer_id, legacy_import_rows.worker_id, legacy_import_rows.worker_employer_id, legacy_import_rows.program_id, legacy_import_rows.client_request_id, legacy_import_rows.training_record_id, legacy_import_rows.protocol_id, legacy_import_rows.protocol_participant_id, legacy_import_rows.moodle_account_id, legacy_import_rows.created_at, legacy_import_rows.updated_at
FROM import_rows
JOIN import_sheets
  ON import_sheets.import_id = import_rows.import_id
 AND import_sheets.sheet_name = import_rows.sheet_name
JOIN legacy_import_rows
  ON legacy_import_rows.import_row_id = import_rows.id
WHERE import_rows.import_id = ?1
  AND legacy_import_rows.status = ?2
  AND (
    import_sheets.sheet_order > ?3
    OR (
      import_sheets.sheet_order = ?3
      AND import_rows.row_number > ?4
    )
    OR (
      import_sheets.sheet_order = ?3
      AND import_rows.row_number = ?4
      AND import_rows.id > ?5
    )
  )
ORDER BY import_sheets.sheet_order ASC, import_rows.row_number ASC, import_rows.id ASC
LIMIT ?6
`

type ListLegacyImportRowsByStatusPageParams struct {
	ImportID        int64  `json:"import_id"`
	StatusFilter    string `json:"status_filter"`
	AfterSheetOrder int64  `json:"after_sheet_order"`
	AfterRowNumber  int64  `json:"after_row_number"`
	AfterID         int64  `json:"after_id"`
	PageSize        int64  `json:"page_size"`
}

type ListLegacyImportRowsByStatusPageRow struct {
	ID                    int64          `json:"id"`
	ImportID              int64          `json:"import_id"`
	SheetName             string         `json:"sheet_name"`
	RowNumber             int64          `json:"row_number"`
	RawData               string         `json:"raw_data"`
	CreatedAt             string         `json:"created_at"`
	SheetOrder            int64          `json:"sheet_order"`
	ImportRowID           int64          `json:"import_row_id"`
	SourceFingerprint     string         `json:"source_fingerprint"`
	EmployerName          sql.NullString `json:"employer_name"`
	InnNormalized         sql.NullString `json:"inn_normalized"`
	LastName              sql.NullString `json:"last_name"`
	FirstName             sql.NullString `json:"first_name"`
	MiddleName            sql.NullString `json:"middle_name"`
	SnilsNormalized       sql.NullString `json:"snils_normalized"`
	EmailNormalized       sql.NullString `json:"email_normalized"`
	Position              sql.NullString `json:"position"`
	Department            sql.NullString `json:"department"`
	ProgramText           sql.NullString `json:"program_text"`
	TrainingStartDate     sql.NullString `json:"training_start_date"`
	TrainingEndDate       sql.NullString `json:"training_end_date"`
	ProtocolNumber        sql.NullString `json:"protocol_number"`
	ProtocolDate          sql.NullString `json:"protocol_date"`
	AssessmentResult      sql.NullString `json:"assessment_result"`
	MintrudRegistryNumber sql.NullString `json:"mintrud_registry_number"`
	SourceReference       sql.NullString `json:"source_reference"`
	MoodleUsername        sql.NullString `json:"moodle_username"`
	MoodleEmail           sql.NullString `json:"moodle_email"`
	ExtraFields           string         `json:"extra_fields"`
	Status                string         `json:"status"`
	Version               int64          `json:"version"`
	EmployerID            sql.NullInt64  `json:"employer_id"`
	WorkerID              sql.NullInt64  `json:"worker_id"`
	WorkerEmployerID      sql.NullInt64  `json:"worker_employer_id"`
	ProgramID             sql.NullInt64  `json:"program_id"`
	ClientRequestID       sql.NullInt64  `json:"client_request_id"`
	TrainingRecordID      sql.NullInt64  `json:"training_record_id"`
	ProtocolID            sql.NullInt64  `json:"protocol_id"`
	ProtocolParticipantID sql.NullInt64  `json:"protocol_participant_id"`
	MoodleAccountID       sql.NullInt64  `json:"moodle_account_id"`
	CreatedAt_2           string         `json:"created_at_2"`
	UpdatedAt             string         `json:"updated_at"`
}

func (q *Queries) ListLegacyImportRowsByStatusPage(ctx context.Context, arg ListLegacyImportRowsByStatusPageParams) ([]ListLegacyImportRowsByStatusPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listLegacyImportRowsByStatusPage,
		arg.ImportID,
		arg.StatusFilter,
		arg.AfterSheetOrder,
		arg.AfterRowNumber,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLegacyImportRowsByStatusPageRow
	for rows.Next() {
		var i ListLegacyImportRowsByStatusPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.SheetName,
			&i.RowNumber,
			&i.RawData,
			&i.CreatedAt,
			&i.SheetOrder,
			&i.ImportRowID,
			&i.SourceFingerprint,
			&i.EmployerName,
			&i.InnNormalized,
			&i.LastName,
			&i.FirstName,
			&i.MiddleName,
			&i.SnilsNormalized,
			&i.EmailNormalized,
			&i.Position,
			&i.Department,
			&i.ProgramText,
			&i.TrainingStartDate,
			&i.TrainingEndDate,
			&i.ProtocolNumber,
			&i.ProtocolDate,
			&i.AssessmentResult,
			&i.MintrudRegistryNumber,
			&i.SourceReference,
			&i.MoodleUsername,
			&i.MoodleEmail,
			&i.ExtraFields,
			&i.Status,
			&i.Version,
			&i.EmployerID,
			&i.WorkerID,
			&i.WorkerEmployerID,
			&i.ProgramID,
			&i.ClientRequestID,
			&i.TrainingRecordID,
			&i.ProtocolID,
			&i.ProtocolParticipantID,
			&i.MoodleAccountID,
			&i.CreatedAt_2,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLegacyImportRowLinks = `-- name: UpdateLegacyImportRowLinks :one
UPDATE legacy_import_rows
SET employer_id = ?,
    worker_id = ?,
    worker_employer_id = ?,
    program_id = ?,
    client_request_id = ?,
    training_record_id = ?,
    protocol_id = ?,
    protocol_participant_id = ?,
    moodle_account_id = ?,
    status = ?,
    version = version + 1,
    updated_at = ?
WHERE import_row_id = ? AND version = ?
RETURNING import_row_id, source_fingerprint, employer_name, inn_normalized, last_name, first_name, middle_name, snils_normalized, email_normalized, position, department, program_text, training_start_date, training_end_date, protocol_number, protocol_date, assessment_result, mintrud_registry_number, source_reference, moodle_username, moodle_email, extra_fields, status, version, employer_id, worker_id, worker_employer_id, program_id, client_request_id, training_record_id, protocol_id, protocol_participant_id, moodle_account_id, created_at, updated_at
`

type UpdateLegacyImportRowLinksParams struct {
	EmployerID            sql.NullInt64 `json:"employer_id"`
	WorkerID              sql.NullInt64 `json:"worker_id"`
	WorkerEmployerID      sql.NullInt64 `json:"worker_employer_id"`
	ProgramID             sql.NullInt64 `json:"program_id"`
	ClientRequestID       sql.NullInt64 `json:"client_request_id"`
	TrainingRecordID      sql.NullInt64 `json:"training_record_id"`
	ProtocolID            sql.NullInt64 `json:"protocol_id"`
	ProtocolParticipantID sql.NullInt64 `json:"protocol_participant_id"`
	MoodleAccountID       sql.NullInt64 `json:"moodle_account_id"`
	Status                string        `json:"status"`
	UpdatedAt             string        `json:"updated_at"`
	ImportRowID           int64         `json:"import_row_id"`
	Version               int64         `json:"version"`
}

func (q *Queries) UpdateLegacyImportRowLinks(ctx context.Context, arg UpdateLegacyImportRowLinksParams) (LegacyImportRow, error) {
	row := q.db.QueryRowContext(ctx, updateLegacyImportRowLinks,
		arg.EmployerID,
		arg.WorkerID,
		arg.WorkerEmployerID,
		arg.ProgramID,
		arg.ClientRequestID,
		arg.TrainingRecordID,
		arg.ProtocolID,
		arg.ProtocolParticipantID,
		arg.MoodleAccountID,
		arg.Status,
		arg.UpdatedAt,
		arg.ImportRowID,
		arg.Version,
	)
	var i LegacyImportRow
	err := row.Scan(
		&i.ImportRowID,
		&i.SourceFingerprint,
		&i.EmployerName,
		&i.InnNormalized,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.SnilsNormalized,
		&i.EmailNormalized,
		&i.Position,
		&i.Department,
		&i.ProgramText,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.ProtocolNumber,
		&i.ProtocolDate,
		&i.AssessmentResult,
		&i.MintrudRegistryNumber,
		&i.SourceReference,
		&i.MoodleUsername,
		&i.MoodleEmail,
		&i.ExtraFields,
		&i.Status,
		&i.Version,
		&i.EmployerID,
		&i.WorkerID,
		&i.WorkerEmployerID,
		&i.ProgramID,
		&i.ClientRequestID,
		&i.TrainingRecordID,
		&i.ProtocolID,
		&i.ProtocolParticipantID,
		&i.MoodleAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLegacyImportRowNormalized = `-- name: UpdateLegacyImportRowNormalized :one
UPDATE legacy_import_rows
SET employer_name = ?,
    inn_normalized = ?,
    last_name = ?,
    first_name = ?,
    middle_name = ?,
    snils_normalized = ?,
    email_normalized = ?,
    position = ?,
    department = ?,
    program_text = ?,
    training_start_date = ?,
    training_end_date = ?,
    protocol_number = ?,
    protocol_date = ?,
    assessment_result = ?,
    mintrud_registry_number = ?,
    source_reference = ?,
    moodle_username = ?,
    moodle_email = ?,
    extra_fields = ?,
    status = ?,
    version = version + 1,
    updated_at = ?
WHERE import_row_id = ? AND version = ?
RETURNING import_row_id, source_fingerprint, employer_name, inn_normalized, last_name, first_name, middle_name, snils_normalized, email_normalized, position, department, program_text, training_start_date, training_end_date, protocol_number, protocol_date, assessment_result, mintrud_registry_number, source_reference, moodle_username, moodle_email, extra_fields, status, version, employer_id, worker_id, worker_employer_id, program_id, client_request_id, training_record_id, protocol_id, protocol_participant_id, moodle_account_id, created_at, updated_at
`

type UpdateLegacyImportRowNormalizedParams struct {
	EmployerName          sql.NullString `json:"employer_name"`
	InnNormalized         sql.NullString `json:"inn_normalized"`
	LastName              sql.NullString `json:"last_name"`
	FirstName             sql.NullString `json:"first_name"`
	MiddleName            sql.NullString `json:"middle_name"`
	SnilsNormalized       sql.NullString `json:"snils_normalized"`
	EmailNormalized       sql.NullString `json:"email_normalized"`
	Position              sql.NullString `json:"position"`
	Department            sql.NullString `json:"department"`
	ProgramText           sql.NullString `json:"program_text"`
	TrainingStartDate     sql.NullString `json:"training_start_date"`
	TrainingEndDate       sql.NullString `json:"training_end_date"`
	ProtocolNumber        sql.NullString `json:"protocol_number"`
	ProtocolDate          sql.NullString `json:"protocol_date"`
	AssessmentResult      sql.NullString `json:"assessment_result"`
	MintrudRegistryNumber sql.NullString `json:"mintrud_registry_number"`
	SourceReference       sql.NullString `json:"source_reference"`
	MoodleUsername        sql.NullString `json:"moodle_username"`
	MoodleEmail           sql.NullString `json:"moodle_email"`
	ExtraFields           string         `json:"extra_fields"`
	Status                string         `json:"status"`
	UpdatedAt             string         `json:"updated_at"`
	ImportRowID           int64          `json:"import_row_id"`
	Version               int64          `json:"version"`
}

func (q *Queries) UpdateLegacyImportRowNormalized(ctx context.Context, arg UpdateLegacyImportRowNormalizedParams) (LegacyImportRow, error) {
	row := q.db.QueryRowContext(ctx, updateLegacyImportRowNormalized,
		arg.EmployerName,
		arg.InnNormalized,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.SnilsNormalized,
		arg.EmailNormalized,
		arg.Position,
		arg.Department,
		arg.ProgramText,
		arg.TrainingStartDate,
		arg.TrainingEndDate,
		arg.ProtocolNumber,
		arg.ProtocolDate,
		arg.AssessmentResult,
		arg.MintrudRegistryNumber,
		arg.SourceReference,
		arg.MoodleUsername,
		arg.MoodleEmail,
		arg.ExtraFields,
		arg.Status,
		arg.UpdatedAt,
		arg.ImportRowID,
		arg.Version,
	)
	var i LegacyImportRow
	err := row.Scan(
		&i.ImportRowID,
		&i.SourceFingerprint,
		&i.EmployerName,
		&i.InnNormalized,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.SnilsNormalized,
		&i.EmailNormalized,
		&i.Position,
		&i.Department,
		&i.ProgramText,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.ProtocolNumber,
		&i.ProtocolDate,
		&i.AssessmentResult,
		&i.MintrudRegistryNumber,
		&i.SourceReference,
		&i.MoodleUsername,
		&i.MoodleEmail,
		&i.ExtraFields,
		&i.Status,
		&i.Version,
		&i.EmployerID,
		&i.WorkerID,
		&i.WorkerEmployerID,
		&i.ProgramID,
		&i.ClientRequestID,
		&i.TrainingRecordID,
		&i.ProtocolID,
		&i.ProtocolParticipantID,
		&i.MoodleAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
