// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type ActionLog struct {
	ID         int64          `json:"id"`
	Actor      string         `json:"actor"`
	Action     string         `json:"action"`
	EntityType string         `json:"entity_type"`
	EntityID   sql.NullInt64  `json:"entity_id"`
	Details    sql.NullString `json:"details"`
	CreatedAt  string         `json:"created_at"`
}

type ClientRequest struct {
	ID             int64          `json:"id"`
	EmployerID     int64          `json:"employer_id"`
	ReceivedDate   string         `json:"received_date"`
	SourceType     string         `json:"source_type"`
	SourceImportID sql.NullInt64  `json:"source_import_id"`
	Status         string         `json:"status"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type Employer struct {
	ID            int64  `json:"id"`
	Inn           string `json:"inn"`
	InnNormalized string `json:"inn_normalized"`
	CanonicalName string `json:"canonical_name"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
	Status        string `json:"status"`
}

type GenerationRun struct {
	ID           int64          `json:"id"`
	ProtocolID   int64          `json:"protocol_id"`
	Type         string         `json:"type"`
	Status       string         `json:"status"`
	FileName     sql.NullString `json:"file_name"`
	GeneratedAt  string         `json:"generated_at"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    string         `json:"created_at"`
}

type Import struct {
	ID              int64          `json:"id"`
	SourceType      string         `json:"source_type"`
	SourceFileName  sql.NullString `json:"source_file_name"`
	SourceSha256    sql.NullString `json:"source_sha256"`
	UploadedByActor string         `json:"uploaded_by_actor"`
	ReceivedAt      string         `json:"received_at"`
	Status          string         `json:"status"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type ImportRow struct {
	ID        int64  `json:"id"`
	ImportID  int64  `json:"import_id"`
	RowNumber int64  `json:"row_number"`
	RawData   string `json:"raw_data"`
	CreatedAt string `json:"created_at"`
}

type MoodleAccount struct {
	ID           int64          `json:"id"`
	WorkerID     int64          `json:"worker_id"`
	MoodleUserID string         `json:"moodle_user_id"`
	Username     string         `json:"username"`
	Email        sql.NullString `json:"email"`
	Idnumber     sql.NullString `json:"idnumber"`
	Status       string         `json:"status"`
	SyncedAt     sql.NullString `json:"synced_at"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type Program struct {
	ID             int64          `json:"id"`
	ProgramGroupID int64          `json:"program_group_id"`
	Code           string         `json:"code"`
	Name           string         `json:"name"`
	DefaultHours   int64          `json:"default_hours"`
	MoodleCourseID sql.NullString `json:"moodle_course_id"`
	Status         string         `json:"status"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type ProgramGroup struct {
	ID        int64  `json:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Protocol struct {
	ID                   int64          `json:"id"`
	ProgramGroupID       int64          `json:"program_group_id"`
	Status               string         `json:"status"`
	TrainingStartDate    sql.NullString `json:"training_start_date"`
	TrainingEndDate      sql.NullString `json:"training_end_date"`
	ProtocolDate         sql.NullString `json:"protocol_date"`
	SequenceYear         sql.NullInt64  `json:"sequence_year"`
	ProtocolMonth        sql.NullInt64  `json:"protocol_month"`
	AnnualSequenceNumber sql.NullInt64  `json:"annual_sequence_number"`
	ProtocolNumber       sql.NullString `json:"protocol_number"`
	FixedAt              sql.NullString `json:"fixed_at"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	ProtocolSuffix       sql.NullString `json:"protocol_suffix"`
}

type ProtocolParticipant struct {
	ID                             int64          `json:"id"`
	ProtocolID                     int64          `json:"protocol_id"`
	TrainingRecordID               int64          `json:"training_record_id"`
	Status                         string         `json:"status"`
	RequiresMintrudTestConfirmedAt sql.NullString `json:"requires_mintrud_test_confirmed_at"`
	MintrudRegistryNumber          sql.NullString `json:"mintrud_registry_number"`
	MintrudRegistryEnteredAt       sql.NullString `json:"mintrud_registry_entered_at"`
	CreatedAt                      string         `json:"created_at"`
	UpdatedAt                      string         `json:"updated_at"`
}

type RequestRow struct {
	ID               int64          `json:"id"`
	ClientRequestID  int64          `json:"client_request_id"`
	RowNumber        int64          `json:"row_number"`
	RawData          string         `json:"raw_data"`
	RawFullName      sql.NullString `json:"raw_full_name"`
	ParsedLastName   sql.NullString `json:"parsed_last_name"`
	ParsedFirstName  sql.NullString `json:"parsed_first_name"`
	ParsedMiddleName sql.NullString `json:"parsed_middle_name"`
	ParsedSnils      sql.NullString `json:"parsed_snils"`
	ParsedEmail      sql.NullString `json:"parsed_email"`
	ParsedPosition   sql.NullString `json:"parsed_position"`
	Status           string         `json:"status"`
	ErrorSummary     sql.NullString `json:"error_summary"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type RequestTrainingItem struct {
	ID               int64          `json:"id"`
	RequestRowID     int64          `json:"request_row_id"`
	ProgramID        int64          `json:"program_id"`
	Status           string         `json:"status"`
	ErrorSummary     sql.NullString `json:"error_summary"`
	Resolution       sql.NullString `json:"resolution"`
	TrainingRecordID sql.NullInt64  `json:"training_record_id"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type TrainingRecord struct {
	ID                  int64          `json:"id"`
	WorkerEmployerID    int64          `json:"worker_employer_id"`
	ProgramID           int64          `json:"program_id"`
	ClientRequestID     sql.NullInt64  `json:"client_request_id"`
	Position            string         `json:"position"`
	Hours               int64          `json:"hours"`
	RequiresMintrudTest int64          `json:"requires_mintrud_test"`
	MoodleStatus        string         `json:"moodle_status"`
	MoodleError         sql.NullString `json:"moodle_error"`
	MoodleEnrolledAt    sql.NullString `json:"moodle_enrolled_at"`
	Status              string         `json:"status"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

type User struct {
	ID           int64  `json:"id"`
	Login        string `json:"login"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Status       string `json:"status"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type Worker struct {
	ID              int64          `json:"id"`
	LastName        string         `json:"last_name"`
	FirstName       string         `json:"first_name"`
	MiddleName      sql.NullString `json:"middle_name"`
	Snils           string         `json:"snils"`
	SnilsNormalized string         `json:"snils_normalized"`
	Email           string         `json:"email"`
	BirthDate       sql.NullString `json:"birth_date"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	Status          string         `json:"status"`
}

type WorkerEmployer struct {
	ID              int64  `json:"id"`
	WorkerID        int64  `json:"worker_id"`
	EmployerID      int64  `json:"employer_id"`
	CurrentPosition string `json:"current_position"`
	Status          string `json:"status"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}
