// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program_groups.sql

package db

import (
	"context"
)

const createProgramGroup = `-- name: CreateProgramGroup :one
INSERT INTO program_groups (
  code,
  name,
  status,
  created_at,
  updated_at
)
VALUES (?, ?, 'active', ?, ?)
RETURNING id, code, name, status, created_at, updated_at
`

type CreateProgramGroupParams struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) CreateProgramGroup(ctx context.Context, arg CreateProgramGroupParams) (ProgramGroup, error) {
	row := q.db.QueryRowContext(ctx, createProgramGroup,
		arg.Code,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProgramGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateGroup = `-- name: DeactivateGroup :one
UPDATE program_groups
SET status = 'inactive',
    updated_at = ?
WHERE id = ?
RETURNING id, code, name, status, created_at, updated_at
`

type DeactivateGroupParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) DeactivateGroup(ctx context.Context, arg DeactivateGroupParams) (ProgramGroup, error) {
	row := q.db.QueryRowContext(ctx, deactivateGroup, arg.UpdatedAt, arg.ID)
	var i ProgramGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, code, name, status, created_at, updated_at
FROM program_groups
WHERE id = ?
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (ProgramGroup, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i ProgramGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgramGroup = `-- name: GetProgramGroup :one
SELECT id, code, name, status, created_at, updated_at
FROM program_groups
WHERE id = ?
`

func (q *Queries) GetProgramGroup(ctx context.Context, id int64) (ProgramGroup, error) {
	row := q.db.QueryRowContext(ctx, getProgramGroup, id)
	var i ProgramGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProgramGroups = `-- name: ListProgramGroups :many
SELECT id, code, name, status, created_at, updated_at
FROM program_groups
ORDER BY code
`

func (q *Queries) ListProgramGroups(ctx context.Context) ([]ProgramGroup, error) {
	rows, err := q.db.QueryContext(ctx, listProgramGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramGroup
	for rows.Next() {
		var i ProgramGroup
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProgramGroupStatus = `-- name: SetProgramGroupStatus :one
UPDATE program_groups
SET status = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, code, name, status, created_at, updated_at
`

type SetProgramGroupStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) SetProgramGroupStatus(ctx context.Context, arg SetProgramGroupStatusParams) (ProgramGroup, error) {
	row := q.db.QueryRowContext(ctx, setProgramGroupStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i ProgramGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE program_groups
SET code = ?,
    name = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, code, name, status, created_at, updated_at
`

type UpdateGroupParams struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (ProgramGroup, error) {
	row := q.db.QueryRowContext(ctx, updateGroup,
		arg.Code,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ProgramGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProgramGroup = `-- name: UpdateProgramGroup :one
UPDATE program_groups
SET code = ?,
    name = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, code, name, status, created_at, updated_at
`

type UpdateProgramGroupParams struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateProgramGroup(ctx context.Context, arg UpdateProgramGroupParams) (ProgramGroup, error) {
	row := q.db.QueryRowContext(ctx, updateProgramGroup,
		arg.Code,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ProgramGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
