// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program_aliases.sql

package db

import (
	"context"
)

const createProgramAlias = `-- name: CreateProgramAlias :one
INSERT INTO program_aliases (
  profile,
  sheet_profile,
  alias_normalized,
  program_id,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, profile, sheet_profile, alias_normalized, program_id, created_at, updated_at
`

type CreateProgramAliasParams struct {
	Profile         string `json:"profile"`
	SheetProfile    string `json:"sheet_profile"`
	AliasNormalized string `json:"alias_normalized"`
	ProgramID       int64  `json:"program_id"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) CreateProgramAlias(ctx context.Context, arg CreateProgramAliasParams) (ProgramAlias, error) {
	row := q.db.QueryRowContext(ctx, createProgramAlias,
		arg.Profile,
		arg.SheetProfile,
		arg.AliasNormalized,
		arg.ProgramID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProgramAlias
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.SheetProfile,
		&i.AliasNormalized,
		&i.ProgramID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgramByAlias = `-- name: GetProgramByAlias :one
SELECT programs.id, programs.program_group_id, programs.code, programs.name, programs.default_hours, programs.moodle_course_id, programs.status, programs.created_at, programs.updated_at
FROM program_aliases
JOIN programs ON programs.id = program_aliases.program_id
WHERE program_aliases.profile = ?
  AND program_aliases.sheet_profile = ?
  AND program_aliases.alias_normalized = ?
LIMIT 1
`

type GetProgramByAliasParams struct {
	Profile         string `json:"profile"`
	SheetProfile    string `json:"sheet_profile"`
	AliasNormalized string `json:"alias_normalized"`
}

func (q *Queries) GetProgramByAlias(ctx context.Context, arg GetProgramByAliasParams) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgramByAlias, arg.Profile, arg.SheetProfile, arg.AliasNormalized)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.ProgramGroupID,
		&i.Code,
		&i.Name,
		&i.DefaultHours,
		&i.MoodleCourseID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProgramAliases = `-- name: ListProgramAliases :many
SELECT id, profile, sheet_profile, alias_normalized, program_id, created_at, updated_at
FROM program_aliases
WHERE profile = ?
ORDER BY sheet_profile ASC, alias_normalized ASC, id ASC
`

func (q *Queries) ListProgramAliases(ctx context.Context, profile string) ([]ProgramAlias, error) {
	rows, err := q.db.QueryContext(ctx, listProgramAliases, profile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramAlias
	for rows.Next() {
		var i ProgramAlias
		if err := rows.Scan(
			&i.ID,
			&i.Profile,
			&i.SheetProfile,
			&i.AliasNormalized,
			&i.ProgramID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
