// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package db

import (
	"context"
	"database/sql"
)

const createProgram = `-- name: CreateProgram :one
INSERT INTO programs (
  program_group_id,
  code,
  name,
  default_hours,
  moodle_course_id,
  status,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, 'active', ?, ?)
RETURNING id, program_group_id, code, name, default_hours, moodle_course_id, status, created_at, updated_at
`

type CreateProgramParams struct {
	ProgramGroupID int64          `json:"program_group_id"`
	Code           string         `json:"code"`
	Name           string         `json:"name"`
	DefaultHours   int64          `json:"default_hours"`
	MoodleCourseID sql.NullString `json:"moodle_course_id"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.db.QueryRowContext(ctx, createProgram,
		arg.ProgramGroupID,
		arg.Code,
		arg.Name,
		arg.DefaultHours,
		arg.MoodleCourseID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.ProgramGroupID,
		&i.Code,
		&i.Name,
		&i.DefaultHours,
		&i.MoodleCourseID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgram = `-- name: GetProgram :one
SELECT id, program_group_id, code, name, default_hours, moodle_course_id, status, created_at, updated_at
FROM programs
WHERE id = ?
`

func (q *Queries) GetProgram(ctx context.Context, id int64) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgram, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.ProgramGroupID,
		&i.Code,
		&i.Name,
		&i.DefaultHours,
		&i.MoodleCourseID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, program_group_id, code, name, default_hours, moodle_course_id, status, created_at, updated_at
FROM programs
ORDER BY code
`

func (q *Queries) ListPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Program
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.ProgramGroupID,
			&i.Code,
			&i.Name,
			&i.DefaultHours,
			&i.MoodleCourseID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByGroup = `-- name: ListProgramsByGroup :many
SELECT id, program_group_id, code, name, default_hours, moodle_course_id, status, created_at, updated_at
FROM programs
WHERE program_group_id = ?
ORDER BY code
`

func (q *Queries) ListProgramsByGroup(ctx context.Context, programGroupID int64) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByGroup, programGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Program
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.ProgramGroupID,
			&i.Code,
			&i.Name,
			&i.DefaultHours,
			&i.MoodleCourseID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProgramStatus = `-- name: SetProgramStatus :one
UPDATE programs
SET status = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, program_group_id, code, name, default_hours, moodle_course_id, status, created_at, updated_at
`

type SetProgramStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) SetProgramStatus(ctx context.Context, arg SetProgramStatusParams) (Program, error) {
	row := q.db.QueryRowContext(ctx, setProgramStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.ProgramGroupID,
		&i.Code,
		&i.Name,
		&i.DefaultHours,
		&i.MoodleCourseID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProgram = `-- name: UpdateProgram :one
UPDATE programs
SET program_group_id = ?,
    code = ?,
    name = ?,
    default_hours = ?,
    moodle_course_id = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, program_group_id, code, name, default_hours, moodle_course_id, status, created_at, updated_at
`

type UpdateProgramParams struct {
	ProgramGroupID int64          `json:"program_group_id"`
	Code           string         `json:"code"`
	Name           string         `json:"name"`
	DefaultHours   int64          `json:"default_hours"`
	MoodleCourseID sql.NullString `json:"moodle_course_id"`
	UpdatedAt      string         `json:"updated_at"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error) {
	row := q.db.QueryRowContext(ctx, updateProgram,
		arg.ProgramGroupID,
		arg.Code,
		arg.Name,
		arg.DefaultHours,
		arg.MoodleCourseID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.ProgramGroupID,
		&i.Code,
		&i.Name,
		&i.DefaultHours,
		&i.MoodleCourseID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
