// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: protocols.sql

package db

import (
	"context"
	"database/sql"
)

const createProtocol = `-- name: CreateProtocol :one
INSERT INTO protocols (
  program_group_id,
  status,
  created_at,
  updated_at
)
VALUES (?, 'draft', ?, ?)
RETURNING id, program_group_id, status, training_start_date, training_end_date,
          protocol_date, sequence_year, protocol_month, annual_sequence_number,
          protocol_number, fixed_at, created_at, updated_at, protocol_suffix
`

type CreateProtocolParams struct {
	ProgramGroupID int64  `json:"program_group_id"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

// Insert a brand-new protocol in 'draft' status. Only program_group_id is
// required; everything else is NULL until Fix is called.
func (q *Queries) CreateProtocol(ctx context.Context, arg CreateProtocolParams) (Protocol, error) {
	row := q.db.QueryRowContext(ctx, createProtocol, arg.ProgramGroupID, arg.CreatedAt, arg.UpdatedAt)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.ProgramGroupID,
		&i.Status,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.ProtocolDate,
		&i.SequenceYear,
		&i.ProtocolMonth,
		&i.AnnualSequenceNumber,
		&i.ProtocolNumber,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProtocolSuffix,
	)
	return i, err
}

const fixProtocol = `-- name: FixProtocol :one
UPDATE protocols
SET status = 'fixed',
    training_start_date = ?,
    training_end_date = ?,
    protocol_date = ?,
    sequence_year = ?,
    protocol_month = ?,
    annual_sequence_number = ?,
    protocol_number = ?,
    protocol_suffix = ?,
    fixed_at = ?,
    updated_at = ?
WHERE id = ? AND status = 'draft'
RETURNING id, program_group_id, status, training_start_date, training_end_date,
          protocol_date, sequence_year, protocol_month, annual_sequence_number,
          protocol_number, fixed_at, created_at, updated_at, protocol_suffix
`

type FixProtocolParams struct {
	TrainingStartDate    sql.NullString `json:"training_start_date"`
	TrainingEndDate      sql.NullString `json:"training_end_date"`
	ProtocolDate         sql.NullString `json:"protocol_date"`
	SequenceYear         sql.NullInt64  `json:"sequence_year"`
	ProtocolMonth        sql.NullInt64  `json:"protocol_month"`
	AnnualSequenceNumber sql.NullInt64  `json:"annual_sequence_number"`
	ProtocolNumber       sql.NullString `json:"protocol_number"`
	ProtocolSuffix       sql.NullString `json:"protocol_suffix"`
	FixedAt              sql.NullString `json:"fixed_at"`
	UpdatedAt            string         `json:"updated_at"`
	ID                   int64          `json:"id"`
}

// Mark a draft protocol as fixed and stamp dates + number atomically.
// The service is responsible for computing sequence_year / protocol_month /
// annual_sequence_number / protocol_number / fixed_at from the request and
// the current MAX sequence for (program_group_id, sequence_year).
func (q *Queries) FixProtocol(ctx context.Context, arg FixProtocolParams) (Protocol, error) {
	row := q.db.QueryRowContext(ctx, fixProtocol,
		arg.TrainingStartDate,
		arg.TrainingEndDate,
		arg.ProtocolDate,
		arg.SequenceYear,
		arg.ProtocolMonth,
		arg.AnnualSequenceNumber,
		arg.ProtocolNumber,
		arg.ProtocolSuffix,
		arg.FixedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.ProgramGroupID,
		&i.Status,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.ProtocolDate,
		&i.SequenceYear,
		&i.ProtocolMonth,
		&i.AnnualSequenceNumber,
		&i.ProtocolNumber,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProtocolSuffix,
	)
	return i, err
}

const getProtocolByID = `-- name: GetProtocolByID :one
SELECT id, program_group_id, status, training_start_date, training_end_date,
       protocol_date, sequence_year, protocol_month, annual_sequence_number,
       protocol_number, fixed_at, created_at, updated_at, protocol_suffix
FROM protocols
WHERE id = ?
`

func (q *Queries) GetProtocolByID(ctx context.Context, id int64) (Protocol, error) {
	row := q.db.QueryRowContext(ctx, getProtocolByID, id)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.ProgramGroupID,
		&i.Status,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.ProtocolDate,
		&i.SequenceYear,
		&i.ProtocolMonth,
		&i.AnnualSequenceNumber,
		&i.ProtocolNumber,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProtocolSuffix,
	)
	return i, err
}

const listProtocols = `-- name: ListProtocols :many
SELECT id, program_group_id, status, training_start_date, training_end_date,
       protocol_date, sequence_year, protocol_month, annual_sequence_number,
       protocol_number, fixed_at, created_at, updated_at, protocol_suffix
FROM protocols
ORDER BY created_at DESC, id DESC
`

// All protocols, newest first. Used by /protocols list view.
func (q *Queries) ListProtocols(ctx context.Context) ([]Protocol, error) {
	rows, err := q.db.QueryContext(ctx, listProtocols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Protocol
	for rows.Next() {
		var i Protocol
		if err := rows.Scan(
			&i.ID,
			&i.ProgramGroupID,
			&i.Status,
			&i.TrainingStartDate,
			&i.TrainingEndDate,
			&i.ProtocolDate,
			&i.SequenceYear,
			&i.ProtocolMonth,
			&i.AnnualSequenceNumber,
			&i.ProtocolNumber,
			&i.FixedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProtocolSuffix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProtocolsByGroup = `-- name: ListProtocolsByGroup :many
SELECT id, program_group_id, status, training_start_date, training_end_date,
       protocol_date, sequence_year, protocol_month, annual_sequence_number,
       protocol_number, fixed_at, created_at, updated_at, protocol_suffix
FROM protocols
WHERE program_group_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProtocolsByGroup(ctx context.Context, programGroupID int64) ([]Protocol, error) {
	rows, err := q.db.QueryContext(ctx, listProtocolsByGroup, programGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Protocol
	for rows.Next() {
		var i Protocol
		if err := rows.Scan(
			&i.ID,
			&i.ProgramGroupID,
			&i.Status,
			&i.TrainingStartDate,
			&i.TrainingEndDate,
			&i.ProtocolDate,
			&i.SequenceYear,
			&i.ProtocolMonth,
			&i.AnnualSequenceNumber,
			&i.ProtocolNumber,
			&i.FixedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProtocolSuffix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProtocolsByStatus = `-- name: ListProtocolsByStatus :many
SELECT id, program_group_id, status, training_start_date, training_end_date,
       protocol_date, sequence_year, protocol_month, annual_sequence_number,
       protocol_number, fixed_at, created_at, updated_at, protocol_suffix
FROM protocols
WHERE status = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProtocolsByStatus(ctx context.Context, status string) ([]Protocol, error) {
	rows, err := q.db.QueryContext(ctx, listProtocolsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Protocol
	for rows.Next() {
		var i Protocol
		if err := rows.Scan(
			&i.ID,
			&i.ProgramGroupID,
			&i.Status,
			&i.TrainingStartDate,
			&i.TrainingEndDate,
			&i.ProtocolDate,
			&i.SequenceYear,
			&i.ProtocolMonth,
			&i.AnnualSequenceNumber,
			&i.ProtocolNumber,
			&i.FixedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProtocolSuffix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxAnnualSequenceForGroupYear = `-- name: MaxAnnualSequenceForGroupYear :one
SELECT MAX(annual_sequence_number) AS max_seq
FROM protocols
WHERE program_group_id = ?
  AND sequence_year = ?
  AND annual_sequence_number IS NOT NULL
`

type MaxAnnualSequenceForGroupYearParams struct {
	ProgramGroupID int64         `json:"program_group_id"`
	SequenceYear   sql.NullInt64 `json:"sequence_year"`
}

// Returns the highest annual_sequence_number already used for a (group, year)
// pair. Returns NULL when no fixed protocol exists yet for that pair; the
// service treats NULL as 0 and adds 1 to assign the next slot.
func (q *Queries) MaxAnnualSequenceForGroupYear(ctx context.Context, arg MaxAnnualSequenceForGroupYearParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxAnnualSequenceForGroupYear, arg.ProgramGroupID, arg.SequenceYear)
	var max_seq interface{}
	err := row.Scan(&max_seq)
	return max_seq, err
}

const setProtocolStatus = `-- name: SetProtocolStatus :one
UPDATE protocols
SET status = ?, updated_at = ?
WHERE id = ?
RETURNING id, program_group_id, status, training_start_date, training_end_date,
          protocol_date, sequence_year, protocol_month, annual_sequence_number,
          protocol_number, fixed_at, created_at, updated_at, protocol_suffix
`

type SetProtocolStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

// Update the lifecycle status. The service validates the transition with
// CanTransition before calling this.
func (q *Queries) SetProtocolStatus(ctx context.Context, arg SetProtocolStatusParams) (Protocol, error) {
	row := q.db.QueryRowContext(ctx, setProtocolStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.ProgramGroupID,
		&i.Status,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.ProtocolDate,
		&i.SequenceYear,
		&i.ProtocolMonth,
		&i.AnnualSequenceNumber,
		&i.ProtocolNumber,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProtocolSuffix,
	)
	return i, err
}
