// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: protocol_participants.sql

package db

import (
	"context"
)

const createProtocolParticipant = `-- name: CreateProtocolParticipant :one
INSERT INTO protocol_participants (
  protocol_id,
  training_record_id,
  status,
  created_at,
  updated_at
)
VALUES (?, ?, 'active', ?, ?)
RETURNING id, protocol_id, training_record_id, status,
          requires_mintrud_test_confirmed_at, mintrud_registry_number,
          mintrud_registry_entered_at, created_at, updated_at
`

type CreateProtocolParticipantParams struct {
	ProtocolID       int64  `json:"protocol_id"`
	TrainingRecordID int64  `json:"training_record_id"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

func (q *Queries) CreateProtocolParticipant(ctx context.Context, arg CreateProtocolParticipantParams) (ProtocolParticipant, error) {
	row := q.db.QueryRowContext(ctx, createProtocolParticipant,
		arg.ProtocolID,
		arg.TrainingRecordID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProtocolParticipant
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.TrainingRecordID,
		&i.Status,
		&i.RequiresMintrudTestConfirmedAt,
		&i.MintrudRegistryNumber,
		&i.MintrudRegistryEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveParticipantForTrainingRecord = `-- name: GetActiveParticipantForTrainingRecord :one
SELECT id, protocol_id, training_record_id, status,
       requires_mintrud_test_confirmed_at, mintrud_registry_number,
       mintrud_registry_entered_at, created_at, updated_at
FROM protocol_participants
WHERE training_record_id = ? AND status = 'active'
LIMIT 1
`

// Returns the active (non-removed) participant row for a training_record, if
// any. Used by AddParticipant to enforce the unique-active-training-record
// constraint at service level so the caller sees a clean validation error
// instead of a SQLite constraint failure.
func (q *Queries) GetActiveParticipantForTrainingRecord(ctx context.Context, trainingRecordID int64) (ProtocolParticipant, error) {
	row := q.db.QueryRowContext(ctx, getActiveParticipantForTrainingRecord, trainingRecordID)
	var i ProtocolParticipant
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.TrainingRecordID,
		&i.Status,
		&i.RequiresMintrudTestConfirmedAt,
		&i.MintrudRegistryNumber,
		&i.MintrudRegistryEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProtocolParticipantByID = `-- name: GetProtocolParticipantByID :one
SELECT id, protocol_id, training_record_id, status,
       requires_mintrud_test_confirmed_at, mintrud_registry_number,
       mintrud_registry_entered_at, created_at, updated_at
FROM protocol_participants
WHERE id = ?
`

func (q *Queries) GetProtocolParticipantByID(ctx context.Context, id int64) (ProtocolParticipant, error) {
	row := q.db.QueryRowContext(ctx, getProtocolParticipantByID, id)
	var i ProtocolParticipant
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.TrainingRecordID,
		&i.Status,
		&i.RequiresMintrudTestConfirmedAt,
		&i.MintrudRegistryNumber,
		&i.MintrudRegistryEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllProtocolParticipants = `-- name: ListAllProtocolParticipants :many
SELECT id, protocol_id, training_record_id, status,
       requires_mintrud_test_confirmed_at, mintrud_registry_number,
       mintrud_registry_entered_at, created_at, updated_at
FROM protocol_participants
WHERE protocol_id = ?
ORDER BY id ASC
`

// Including removed participants (kept for audit). Used by integration tests.
func (q *Queries) ListAllProtocolParticipants(ctx context.Context, protocolID int64) ([]ProtocolParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listAllProtocolParticipants, protocolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProtocolParticipant
	for rows.Next() {
		var i ProtocolParticipant
		if err := rows.Scan(
			&i.ID,
			&i.ProtocolID,
			&i.TrainingRecordID,
			&i.Status,
			&i.RequiresMintrudTestConfirmedAt,
			&i.MintrudRegistryNumber,
			&i.MintrudRegistryEnteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProtocolParticipants = `-- name: ListProtocolParticipants :many
SELECT id, protocol_id, training_record_id, status,
       requires_mintrud_test_confirmed_at, mintrud_registry_number,
       mintrud_registry_entered_at, created_at, updated_at
FROM protocol_participants
WHERE protocol_id = ? AND status = 'active'
ORDER BY id ASC
`

// Active participants for a protocol. Used by the detail view.
func (q *Queries) ListProtocolParticipants(ctx context.Context, protocolID int64) ([]ProtocolParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listProtocolParticipants, protocolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProtocolParticipant
	for rows.Next() {
		var i ProtocolParticipant
		if err := rows.Scan(
			&i.ID,
			&i.ProtocolID,
			&i.TrainingRecordID,
			&i.Status,
			&i.RequiresMintrudTestConfirmedAt,
			&i.MintrudRegistryNumber,
			&i.MintrudRegistryEnteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markParticipantRemoved = `-- name: MarkParticipantRemoved :one
UPDATE protocol_participants
SET status = 'removed', updated_at = ?
WHERE id = ? AND status = 'active'
RETURNING id, protocol_id, training_record_id, status,
          requires_mintrud_test_confirmed_at, mintrud_registry_number,
          mintrud_registry_entered_at, created_at, updated_at
`

type MarkParticipantRemovedParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

// Soft-delete: flips status to 'removed' instead of physically deleting.
func (q *Queries) MarkParticipantRemoved(ctx context.Context, arg MarkParticipantRemovedParams) (ProtocolParticipant, error) {
	row := q.db.QueryRowContext(ctx, markParticipantRemoved, arg.UpdatedAt, arg.ID)
	var i ProtocolParticipant
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.TrainingRecordID,
		&i.Status,
		&i.RequiresMintrudTestConfirmedAt,
		&i.MintrudRegistryNumber,
		&i.MintrudRegistryEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
