// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request_training_items.sql

package db

import (
	"context"
	"database/sql"
)

const createRequestTrainingItem = `-- name: CreateRequestTrainingItem :one
INSERT INTO request_training_items (
  request_row_id,
  program_id,
  status,
  error_summary,
  resolution,
  training_record_id,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, request_row_id, program_id, status, error_summary, resolution, training_record_id, created_at, updated_at
`

type CreateRequestTrainingItemParams struct {
	RequestRowID     int64          `json:"request_row_id"`
	ProgramID        int64          `json:"program_id"`
	Status           string         `json:"status"`
	ErrorSummary     sql.NullString `json:"error_summary"`
	Resolution       sql.NullString `json:"resolution"`
	TrainingRecordID sql.NullInt64  `json:"training_record_id"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) CreateRequestTrainingItem(ctx context.Context, arg CreateRequestTrainingItemParams) (RequestTrainingItem, error) {
	row := q.db.QueryRowContext(ctx, createRequestTrainingItem,
		arg.RequestRowID,
		arg.ProgramID,
		arg.Status,
		arg.ErrorSummary,
		arg.Resolution,
		arg.TrainingRecordID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RequestTrainingItem
	err := row.Scan(
		&i.ID,
		&i.RequestRowID,
		&i.ProgramID,
		&i.Status,
		&i.ErrorSummary,
		&i.Resolution,
		&i.TrainingRecordID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestTrainingItem = `-- name: GetRequestTrainingItem :one
SELECT id, request_row_id, program_id, status, error_summary, resolution, training_record_id, created_at, updated_at
FROM request_training_items
WHERE id = ?
`

func (q *Queries) GetRequestTrainingItem(ctx context.Context, id int64) (RequestTrainingItem, error) {
	row := q.db.QueryRowContext(ctx, getRequestTrainingItem, id)
	var i RequestTrainingItem
	err := row.Scan(
		&i.ID,
		&i.RequestRowID,
		&i.ProgramID,
		&i.Status,
		&i.ErrorSummary,
		&i.Resolution,
		&i.TrainingRecordID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRequestTrainingItems = `-- name: ListRequestTrainingItems :many
SELECT id, request_row_id, program_id, status, error_summary, resolution, training_record_id, created_at, updated_at
FROM request_training_items
WHERE request_row_id = ?
ORDER BY id ASC
`

func (q *Queries) ListRequestTrainingItems(ctx context.Context, requestRowID int64) ([]RequestTrainingItem, error) {
	rows, err := q.db.QueryContext(ctx, listRequestTrainingItems, requestRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestTrainingItem
	for rows.Next() {
		var i RequestTrainingItem
		if err := rows.Scan(
			&i.ID,
			&i.RequestRowID,
			&i.ProgramID,
			&i.Status,
			&i.ErrorSummary,
			&i.Resolution,
			&i.TrainingRecordID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestTrainingItemsForRow = `-- name: ListRequestTrainingItemsForRow :many
SELECT rti.id, rti.request_row_id, rti.program_id, rti.status, rti.error_summary, rti.resolution, rti.training_record_id, rti.created_at, rti.updated_at,
       p.code AS program_code, p.name AS program_name, p.default_hours AS program_default_hours
FROM request_training_items rti
JOIN programs p ON p.id = rti.program_id
WHERE rti.request_row_id = ?
ORDER BY rti.id ASC
`

type ListRequestTrainingItemsForRowRow struct {
	ID                  int64          `json:"id"`
	RequestRowID        int64          `json:"request_row_id"`
	ProgramID           int64          `json:"program_id"`
	Status              string         `json:"status"`
	ErrorSummary        sql.NullString `json:"error_summary"`
	Resolution          sql.NullString `json:"resolution"`
	TrainingRecordID    sql.NullInt64  `json:"training_record_id"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
	ProgramCode         string         `json:"program_code"`
	ProgramName         string         `json:"program_name"`
	ProgramDefaultHours int64          `json:"program_default_hours"`
}

func (q *Queries) ListRequestTrainingItemsForRow(ctx context.Context, requestRowID int64) ([]ListRequestTrainingItemsForRowRow, error) {
	rows, err := q.db.QueryContext(ctx, listRequestTrainingItemsForRow, requestRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestTrainingItemsForRowRow
	for rows.Next() {
		var i ListRequestTrainingItemsForRowRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestRowID,
			&i.ProgramID,
			&i.Status,
			&i.ErrorSummary,
			&i.Resolution,
			&i.TrainingRecordID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProgramCode,
			&i.ProgramName,
			&i.ProgramDefaultHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequestTrainingItemStatus = `-- name: UpdateRequestTrainingItemStatus :one
UPDATE request_training_items
SET status = ?,
    error_summary = ?,
    resolution = ?,
    training_record_id = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, request_row_id, program_id, status, error_summary, resolution, training_record_id, created_at, updated_at
`

type UpdateRequestTrainingItemStatusParams struct {
	Status           string         `json:"status"`
	ErrorSummary     sql.NullString `json:"error_summary"`
	Resolution       sql.NullString `json:"resolution"`
	TrainingRecordID sql.NullInt64  `json:"training_record_id"`
	UpdatedAt        string         `json:"updated_at"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateRequestTrainingItemStatus(ctx context.Context, arg UpdateRequestTrainingItemStatusParams) (RequestTrainingItem, error) {
	row := q.db.QueryRowContext(ctx, updateRequestTrainingItemStatus,
		arg.Status,
		arg.ErrorSummary,
		arg.Resolution,
		arg.TrainingRecordID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i RequestTrainingItem
	err := row.Scan(
		&i.ID,
		&i.RequestRowID,
		&i.ProgramID,
		&i.Status,
		&i.ErrorSummary,
		&i.Resolution,
		&i.TrainingRecordID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
