// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request_rows.sql

package db

import (
	"context"
	"database/sql"
)

const createRequestRow = `-- name: CreateRequestRow :one
INSERT INTO request_rows (
  client_request_id,
  row_number,
  raw_data,
  raw_full_name,
  parsed_last_name,
  parsed_first_name,
  parsed_middle_name,
  parsed_snils,
  parsed_email,
  parsed_position,
  status,
  error_summary,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, client_request_id, row_number, raw_data, raw_full_name, parsed_last_name, parsed_first_name, parsed_middle_name, parsed_snils, parsed_email, parsed_position, status, error_summary, created_at, updated_at
`

type CreateRequestRowParams struct {
	ClientRequestID  int64          `json:"client_request_id"`
	RowNumber        int64          `json:"row_number"`
	RawData          string         `json:"raw_data"`
	RawFullName      sql.NullString `json:"raw_full_name"`
	ParsedLastName   sql.NullString `json:"parsed_last_name"`
	ParsedFirstName  sql.NullString `json:"parsed_first_name"`
	ParsedMiddleName sql.NullString `json:"parsed_middle_name"`
	ParsedSnils      sql.NullString `json:"parsed_snils"`
	ParsedEmail      sql.NullString `json:"parsed_email"`
	ParsedPosition   sql.NullString `json:"parsed_position"`
	Status           string         `json:"status"`
	ErrorSummary     sql.NullString `json:"error_summary"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) CreateRequestRow(ctx context.Context, arg CreateRequestRowParams) (RequestRow, error) {
	row := q.db.QueryRowContext(ctx, createRequestRow,
		arg.ClientRequestID,
		arg.RowNumber,
		arg.RawData,
		arg.RawFullName,
		arg.ParsedLastName,
		arg.ParsedFirstName,
		arg.ParsedMiddleName,
		arg.ParsedSnils,
		arg.ParsedEmail,
		arg.ParsedPosition,
		arg.Status,
		arg.ErrorSummary,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RequestRow
	err := row.Scan(
		&i.ID,
		&i.ClientRequestID,
		&i.RowNumber,
		&i.RawData,
		&i.RawFullName,
		&i.ParsedLastName,
		&i.ParsedFirstName,
		&i.ParsedMiddleName,
		&i.ParsedSnils,
		&i.ParsedEmail,
		&i.ParsedPosition,
		&i.Status,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestRow = `-- name: GetRequestRow :one
SELECT id, client_request_id, row_number, raw_data, raw_full_name, parsed_last_name, parsed_first_name, parsed_middle_name, parsed_snils, parsed_email, parsed_position, status, error_summary, created_at, updated_at
FROM request_rows
WHERE id = ?
`

func (q *Queries) GetRequestRow(ctx context.Context, id int64) (RequestRow, error) {
	row := q.db.QueryRowContext(ctx, getRequestRow, id)
	var i RequestRow
	err := row.Scan(
		&i.ID,
		&i.ClientRequestID,
		&i.RowNumber,
		&i.RawData,
		&i.RawFullName,
		&i.ParsedLastName,
		&i.ParsedFirstName,
		&i.ParsedMiddleName,
		&i.ParsedSnils,
		&i.ParsedEmail,
		&i.ParsedPosition,
		&i.Status,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRequestRows = `-- name: ListRequestRows :many
SELECT id, client_request_id, row_number, raw_data, raw_full_name, parsed_last_name, parsed_first_name, parsed_middle_name, parsed_snils, parsed_email, parsed_position, status, error_summary, created_at, updated_at
FROM request_rows
WHERE client_request_id = ?
ORDER BY row_number ASC, id ASC
`

func (q *Queries) ListRequestRows(ctx context.Context, clientRequestID int64) ([]RequestRow, error) {
	rows, err := q.db.QueryContext(ctx, listRequestRows, clientRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestRow
	for rows.Next() {
		var i RequestRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientRequestID,
			&i.RowNumber,
			&i.RawData,
			&i.RawFullName,
			&i.ParsedLastName,
			&i.ParsedFirstName,
			&i.ParsedMiddleName,
			&i.ParsedSnils,
			&i.ParsedEmail,
			&i.ParsedPosition,
			&i.Status,
			&i.ErrorSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequestRowParsed = `-- name: UpdateRequestRowParsed :one
UPDATE request_rows
SET raw_full_name = ?,
    parsed_last_name = ?,
    parsed_first_name = ?,
    parsed_middle_name = ?,
    parsed_snils = ?,
    parsed_email = ?,
    parsed_position = ?,
    status = ?,
    error_summary = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, client_request_id, row_number, raw_data, raw_full_name, parsed_last_name, parsed_first_name, parsed_middle_name, parsed_snils, parsed_email, parsed_position, status, error_summary, created_at, updated_at
`

type UpdateRequestRowParsedParams struct {
	RawFullName      sql.NullString `json:"raw_full_name"`
	ParsedLastName   sql.NullString `json:"parsed_last_name"`
	ParsedFirstName  sql.NullString `json:"parsed_first_name"`
	ParsedMiddleName sql.NullString `json:"parsed_middle_name"`
	ParsedSnils      sql.NullString `json:"parsed_snils"`
	ParsedEmail      sql.NullString `json:"parsed_email"`
	ParsedPosition   sql.NullString `json:"parsed_position"`
	Status           string         `json:"status"`
	ErrorSummary     sql.NullString `json:"error_summary"`
	UpdatedAt        string         `json:"updated_at"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateRequestRowParsed(ctx context.Context, arg UpdateRequestRowParsedParams) (RequestRow, error) {
	row := q.db.QueryRowContext(ctx, updateRequestRowParsed,
		arg.RawFullName,
		arg.ParsedLastName,
		arg.ParsedFirstName,
		arg.ParsedMiddleName,
		arg.ParsedSnils,
		arg.ParsedEmail,
		arg.ParsedPosition,
		arg.Status,
		arg.ErrorSummary,
		arg.UpdatedAt,
		arg.ID,
	)
	var i RequestRow
	err := row.Scan(
		&i.ID,
		&i.ClientRequestID,
		&i.RowNumber,
		&i.RawData,
		&i.RawFullName,
		&i.ParsedLastName,
		&i.ParsedFirstName,
		&i.ParsedMiddleName,
		&i.ParsedSnils,
		&i.ParsedEmail,
		&i.ParsedPosition,
		&i.Status,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRequestRowStatus = `-- name: UpdateRequestRowStatus :one
UPDATE request_rows
SET status = ?,
    error_summary = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, client_request_id, row_number, raw_data, raw_full_name, parsed_last_name, parsed_first_name, parsed_middle_name, parsed_snils, parsed_email, parsed_position, status, error_summary, created_at, updated_at
`

type UpdateRequestRowStatusParams struct {
	Status       string         `json:"status"`
	ErrorSummary sql.NullString `json:"error_summary"`
	UpdatedAt    string         `json:"updated_at"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateRequestRowStatus(ctx context.Context, arg UpdateRequestRowStatusParams) (RequestRow, error) {
	row := q.db.QueryRowContext(ctx, updateRequestRowStatus,
		arg.Status,
		arg.ErrorSummary,
		arg.UpdatedAt,
		arg.ID,
	)
	var i RequestRow
	err := row.Scan(
		&i.ID,
		&i.ClientRequestID,
		&i.RowNumber,
		&i.RawData,
		&i.RawFullName,
		&i.ParsedLastName,
		&i.ParsedFirstName,
		&i.ParsedMiddleName,
		&i.ParsedSnils,
		&i.ParsedEmail,
		&i.ParsedPosition,
		&i.Status,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
