// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training_records.sql

package db

import (
	"context"
)

const getTrainingRecord = `-- name: GetTrainingRecord :one
SELECT id, worker_employer_id, program_id, client_request_id, position, hours,
       requires_mintrud_test, moodle_status, moodle_error, moodle_enrolled_at,
       status, created_at, updated_at
FROM training_records
WHERE id = ?
`

// Returns a single training record by id, used by the protocols slice
// to enrich the participant table with program/position info. Kept in
// its own file (rather than people.sql) so the protocols slice can
// reach into the storage layer without taking a dependency on the
// people service.
func (q *Queries) GetTrainingRecord(ctx context.Context, id int64) (TrainingRecord, error) {
	row := q.db.QueryRowContext(ctx, getTrainingRecord, id)
	var i TrainingRecord
	err := row.Scan(
		&i.ID,
		&i.WorkerEmployerID,
		&i.ProgramID,
		&i.ClientRequestID,
		&i.Position,
		&i.Hours,
		&i.RequiresMintrudTest,
		&i.MoodleStatus,
		&i.MoodleError,
		&i.MoodleEnrolledAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
