// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workers.sql

package db

import (
	"context"
	"database/sql"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (
  last_name,
  first_name,
  middle_name,
  snils,
  snils_normalized,
  email,
  birth_date,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, last_name, first_name, middle_name, snils, snils_normalized, email, birth_date, created_at, updated_at
`

type CreateWorkerParams struct {
	LastName        string         `json:"last_name"`
	FirstName       string         `json:"first_name"`
	MiddleName      sql.NullString `json:"middle_name"`
	Snils           string         `json:"snils"`
	SnilsNormalized string         `json:"snils_normalized"`
	Email           string         `json:"email"`
	BirthDate       sql.NullString `json:"birth_date"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.Snils,
		arg.SnilsNormalized,
		arg.Email,
		arg.BirthDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Snils,
		&i.SnilsNormalized,
		&i.Email,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorker = `-- name: GetWorker :one
SELECT id, last_name, first_name, middle_name, snils, snils_normalized, email, birth_date, created_at, updated_at
FROM workers
WHERE id = ?
`

func (q *Queries) GetWorker(ctx context.Context, id int64) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Snils,
		&i.SnilsNormalized,
		&i.Email,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkerByNormalizedSNILS = `-- name: GetWorkerByNormalizedSNILS :one
SELECT id, last_name, first_name, middle_name, snils, snils_normalized, email, birth_date, created_at, updated_at
FROM workers
WHERE snils_normalized = ?
`

func (q *Queries) GetWorkerByNormalizedSNILS(ctx context.Context, snilsNormalized string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByNormalizedSNILS, snilsNormalized)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Snils,
		&i.SnilsNormalized,
		&i.Email,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, last_name, first_name, middle_name, snils, snils_normalized, email, birth_date, created_at, updated_at
FROM workers
ORDER BY last_name, first_name, middle_name
`

func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.FirstName,
			&i.MiddleName,
			&i.Snils,
			&i.SnilsNormalized,
			&i.Email,
			&i.BirthDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWorkers = `-- name: SearchWorkers :many
SELECT id, last_name, first_name, middle_name, snils, snils_normalized, email, birth_date, created_at, updated_at
FROM workers
WHERE last_name LIKE ? OR first_name LIKE ? OR snils_normalized LIKE ? OR email LIKE ?
ORDER BY last_name, first_name, middle_name
`

type SearchWorkersParams struct {
	LastName        string `json:"last_name"`
	FirstName       string `json:"first_name"`
	SnilsNormalized string `json:"snils_normalized"`
	Email           string `json:"email"`
}

func (q *Queries) SearchWorkers(ctx context.Context, arg SearchWorkersParams) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, searchWorkers,
		arg.LastName,
		arg.FirstName,
		arg.SnilsNormalized,
		arg.Email,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.FirstName,
			&i.MiddleName,
			&i.Snils,
			&i.SnilsNormalized,
			&i.Email,
			&i.BirthDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorker = `-- name: UpdateWorker :one
UPDATE workers
SET last_name = ?,
    first_name = ?,
    middle_name = ?,
    snils = ?,
    snils_normalized = ?,
    email = ?,
    birth_date = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, last_name, first_name, middle_name, snils, snils_normalized, email, birth_date, created_at, updated_at
`

type UpdateWorkerParams struct {
	LastName        string         `json:"last_name"`
	FirstName       string         `json:"first_name"`
	MiddleName      sql.NullString `json:"middle_name"`
	Snils           string         `json:"snils"`
	SnilsNormalized string         `json:"snils_normalized"`
	Email           string         `json:"email"`
	BirthDate       sql.NullString `json:"birth_date"`
	UpdatedAt       string         `json:"updated_at"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, updateWorker,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.Snils,
		arg.SnilsNormalized,
		arg.Email,
		arg.BirthDate,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Snils,
		&i.SnilsNormalized,
		&i.Email,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
