// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker_employers.sql

package db

import (
	"context"
)

const createWorkerEmployer = `-- name: CreateWorkerEmployer :one
INSERT INTO worker_employers (
  worker_id,
  employer_id,
  current_position,
  status,
  created_at,
  updated_at
)
VALUES (?, ?, ?, 'active', ?, ?)
RETURNING id, worker_id, employer_id, current_position, status, created_at, updated_at
`

type CreateWorkerEmployerParams struct {
	WorkerID        int64  `json:"worker_id"`
	EmployerID      int64  `json:"employer_id"`
	CurrentPosition string `json:"current_position"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) CreateWorkerEmployer(ctx context.Context, arg CreateWorkerEmployerParams) (WorkerEmployer, error) {
	row := q.db.QueryRowContext(ctx, createWorkerEmployer,
		arg.WorkerID,
		arg.EmployerID,
		arg.CurrentPosition,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WorkerEmployer
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.EmployerID,
		&i.CurrentPosition,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkerEmployer = `-- name: GetWorkerEmployer :one
SELECT id, worker_id, employer_id, current_position, status, created_at, updated_at
FROM worker_employers
WHERE id = ?
`

func (q *Queries) GetWorkerEmployer(ctx context.Context, id int64) (WorkerEmployer, error) {
	row := q.db.QueryRowContext(ctx, getWorkerEmployer, id)
	var i WorkerEmployer
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.EmployerID,
		&i.CurrentPosition,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkerEmployerAssignments = `-- name: ListWorkerEmployerAssignments :many
SELECT
  worker_employers.id,
  worker_employers.worker_id,
  workers.last_name AS worker_last_name,
  workers.first_name AS worker_first_name,
  worker_employers.employer_id,
  employers.canonical_name AS employer_name,
  worker_employers.current_position,
  worker_employers.status
FROM worker_employers
JOIN workers ON workers.id = worker_employers.worker_id
JOIN employers ON employers.id = worker_employers.employer_id
ORDER BY worker_employers.status, workers.last_name, workers.first_name, employers.canonical_name
`

type ListWorkerEmployerAssignmentsRow struct {
	ID              int64  `json:"id"`
	WorkerID        int64  `json:"worker_id"`
	WorkerLastName  string `json:"worker_last_name"`
	WorkerFirstName string `json:"worker_first_name"`
	EmployerID      int64  `json:"employer_id"`
	EmployerName    string `json:"employer_name"`
	CurrentPosition string `json:"current_position"`
	Status          string `json:"status"`
}

func (q *Queries) ListWorkerEmployerAssignments(ctx context.Context) ([]ListWorkerEmployerAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerEmployerAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkerEmployerAssignmentsRow
	for rows.Next() {
		var i ListWorkerEmployerAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.WorkerLastName,
			&i.WorkerFirstName,
			&i.EmployerID,
			&i.EmployerName,
			&i.CurrentPosition,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerEmployersForWorker = `-- name: ListWorkerEmployersForWorker :many
SELECT id, worker_id, employer_id, current_position, status, created_at, updated_at
FROM worker_employers
WHERE worker_id = ?
ORDER BY status, updated_at DESC
`

func (q *Queries) ListWorkerEmployersForWorker(ctx context.Context, workerID int64) ([]WorkerEmployer, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerEmployersForWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerEmployer
	for rows.Next() {
		var i WorkerEmployer
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.EmployerID,
			&i.CurrentPosition,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersForEmployer = `-- name: ListWorkersForEmployer :many
SELECT id, worker_id, employer_id, current_position, status, created_at, updated_at
FROM worker_employers
WHERE employer_id = ?
ORDER BY status, updated_at DESC
`

func (q *Queries) ListWorkersForEmployer(ctx context.Context, employerID int64) ([]WorkerEmployer, error) {
	rows, err := q.db.QueryContext(ctx, listWorkersForEmployer, employerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerEmployer
	for rows.Next() {
		var i WorkerEmployer
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.EmployerID,
			&i.CurrentPosition,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkerEmployerStatus = `-- name: SetWorkerEmployerStatus :one
UPDATE worker_employers
SET status = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, worker_id, employer_id, current_position, status, created_at, updated_at
`

type SetWorkerEmployerStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) SetWorkerEmployerStatus(ctx context.Context, arg SetWorkerEmployerStatusParams) (WorkerEmployer, error) {
	row := q.db.QueryRowContext(ctx, setWorkerEmployerStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i WorkerEmployer
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.EmployerID,
		&i.CurrentPosition,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkerEmployer = `-- name: UpdateWorkerEmployer :one
UPDATE worker_employers
SET employer_id = ?,
    current_position = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, worker_id, employer_id, current_position, status, created_at, updated_at
`

type UpdateWorkerEmployerParams struct {
	EmployerID      int64  `json:"employer_id"`
	CurrentPosition string `json:"current_position"`
	UpdatedAt       string `json:"updated_at"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateWorkerEmployer(ctx context.Context, arg UpdateWorkerEmployerParams) (WorkerEmployer, error) {
	row := q.db.QueryRowContext(ctx, updateWorkerEmployer,
		arg.EmployerID,
		arg.CurrentPosition,
		arg.UpdatedAt,
		arg.ID,
	)
	var i WorkerEmployer
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.EmployerID,
		&i.CurrentPosition,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
